apiVersion: v1
kind: ConfigMap
metadata:
  name: velox-config
  namespace: velox
  labels:
    app.kubernetes.io/name: velox
data:
  RUN_MIGRATIONS_ON_BOOT: "true"
  LOG_LEVEL: "info"
  APP_ENV: "production"
  PORT: "8080"
  CORS_ALLOWED_ORIGINS: "https://app.velox.dev"
