apiVersion: v1
kind: Secret
metadata:
  name: {{ include "velox.fullname" . }}-secrets
  labels:
    {{- include "velox.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripeSecretKey | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.stripeWebhookSecret | quote }}
  SMTP_HOST: {{ .Values.secrets.smtpHost | quote }}
  SMTP_USERNAME: {{ .Values.secrets.smtpUsername | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
