package importstripe

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/stripe/stripe-go/v82"

	"github.com/sagarsuperuser/velox/internal/domain"
)

// MappedInvoice is the result of translating a Stripe invoice into Velox
// shape. Phase 3 maps each finalized Stripe Invoice (status in {paid, void,
// uncollectible}) onto a `domain.Invoice` plus 1..N `domain.InvoiceLineItem`
// rows. The driver layer fills in CustomerID and SubscriptionID after
// looking up the matching Velox rows by Stripe external id.
//
// The Invoice carries the Stripe-side `in_xxx` id in StripeInvoiceID — the
// natural dedup key the partial unique index from migration 0063 enforces,
// and the lookup the driver uses for idempotent reruns.
type MappedInvoice struct {
	// Invoice is the row to insert. CustomerID + SubscriptionID are populated
	// by the driver after lookup. PaidAt and VoidedAt come straight from
	// Stripe's status_transitions so the imported invoice is faithful to the
	// upstream timeline. InvoiceNumber is left empty — the importer doesn't
	// allocate a Velox sequential number for imported rows (they pre-date
	// Velox's own numbering); the dashboard surfaces them by stripe_invoice_id.
	Invoice domain.Invoice

	// LineItems are the per-line rows to insert atomically with the parent
	// invoice. AmountCents, UnitAmountCents, BillingPeriodStart/End, and
	// Description come verbatim from Stripe's lines.data[].
	LineItems []domain.InvoiceLineItem

	// CustomerExternalID is the Stripe `cus_...` id the driver uses to look
	// up the corresponding Velox customer. Always non-empty after a
	// successful map.
	CustomerExternalID string

	// SubscriptionExternalID is the Stripe `sub_...` id when the invoice
	// was generated by a subscription, otherwise empty (e.g. manual
	// one-off invoices). Extracted from parent.subscription_details
	// preferentially, falling back to lines[0].subscription / lines[0].
	// parent.subscription_item_details.subscription for older payloads.
	// The driver resolves this via subscription.code = `sub_...`.
	SubscriptionExternalID string

	// Notes accumulates non-fatal mapping observations (lossy fields, status
	// remaps, billing-reason remaps). Surfaced in the CSV report on every
	// outcome so operators can audit translations.
	Notes []string
}

// Sentinel errors for unsupported Stripe invoice shapes. The driver
// converts these into ActionError rows in the CSV report so operators can
// post-process them manually without aborting the run.
var (
	// ErrMapEmptyInvoiceID — Stripe invoice with no ID. Malformed.
	ErrMapEmptyInvoiceID = errors.New("stripe invoice has empty id")

	// ErrInvoiceUnsupportedStatus — Phase 3 imports finalized invoices only
	// (status in {paid, void, uncollectible}). Drafts and open invoices are
	// rejected: drafts haven't committed numbering / state in Stripe, and
	// open invoices represent in-flight collection that Velox would need to
	// take over — the importer's "snapshot at a point in time" model
	// doesn't fit. Operators run dunning + payment retry on the Stripe side
	// and re-import after settlement.
	ErrInvoiceUnsupportedStatus = errors.New("stripe invoice is not finalized; Phase 3 only imports paid / void / uncollectible invoices")

	// ErrInvoiceMissingCustomer — invoice has no customer reference.
	// Malformed Stripe response (invoices always have a customer in v82).
	ErrInvoiceMissingCustomer = errors.New("stripe invoice has no customer reference")

	// ErrInvoiceMissingLineItems — invoice with no lines. Stripe rarely
	// finalizes empty invoices, but defensively guarded.
	ErrInvoiceMissingLineItems = errors.New("stripe invoice has no line items")
)

// mapInvoice translates a *stripe.Invoice into Velox shape. Pure: no DB / no
// Stripe API. The driver layer handles customer + subscription lookup
// (those need DB access) before inserting the resulting Invoice.
//
// Status mapping policy (Velox status enum is narrower than Stripe's):
//   - paid → InvoicePaid + PaymentSucceeded
//   - void → InvoiceVoided + PaymentFailed (PaymentFailed is the closest
//     terminal payment status; Velox lacks a "voided" payment-status
//     concept)
//   - uncollectible → InvoiceVoided + PaymentFailed + note (Velox has no
//     uncollectible status — the closest terminal state is voided, with
//     the note preserving the original Stripe distinction for audit)
//   - draft / open → ErrInvoiceUnsupportedStatus
//
// Billing-reason mapping (Stripe's enum is broader than Velox's):
//   - subscription_create → BillingReasonSubscriptionCreate
//   - subscription_cycle → BillingReasonSubscriptionCycle
//   - subscription_threshold → BillingReasonThreshold
//   - manual → BillingReasonManual
//   - subscription_update → BillingReasonManual + note (Velox has no
//     update reason; manual is the most accurate fallback for a
//     proration / mid-cycle change-driven invoice)
//   - subscription (legacy pre-2018) → BillingReasonSubscriptionCycle + note
//   - quote_accept / automatic_pending_invoice_item_invoice / upcoming →
//     BillingReasonManual + note
//   - empty → BillingReasonManual + note
//
// Lossy mappings noted in the report:
//   - discounts (Velox coupon system is independent; operators must reapply)
//   - amount_shipping (Velox doesn't model shipping as a first-class line)
//   - default_tax_rates (Velox tax handling is per-tenant via the tax
//     provider, not per-invoice rate IDs)
//   - tax / total_taxes (preserved verbatim into TaxAmountCents but the
//     per-tax-rate breakdown is not modelled)
//   - rendering / hosted_invoice_url (Velox generates its own hosted URL
//     via public_token at finalize; the Stripe URL is dropped)
func mapInvoice(inv *stripe.Invoice) (MappedInvoice, error) {
	if inv == nil {
		return MappedInvoice{}, errors.New("nil stripe invoice")
	}
	if strings.TrimSpace(inv.ID) == "" {
		return MappedInvoice{}, ErrMapEmptyInvoiceID
	}

	if inv.Customer == nil || strings.TrimSpace(inv.Customer.ID) == "" {
		return MappedInvoice{}, ErrInvoiceMissingCustomer
	}

	// Status filter: reject non-finalized invoices up front. The driver
	// will surface this as ActionError so the operator sees what was
	// skipped rather than silently dropping rows.
	veloxStatus, paymentStatus, statusNote, err := mapInvoiceStatus(inv.Status)
	if err != nil {
		return MappedInvoice{}, err
	}

	if inv.Lines == nil || len(inv.Lines.Data) == 0 {
		return MappedInvoice{}, ErrInvoiceMissingLineItems
	}

	var notes []string
	if statusNote != "" {
		notes = append(notes, statusNote)
	}

	veloxBillingReason, billingReasonNote := mapInvoiceBillingReason(inv.BillingReason)
	if billingReasonNote != "" {
		notes = append(notes, billingReasonNote)
	}

	currency := strings.ToUpper(strings.TrimSpace(string(inv.Currency)))

	// Billing period: prefer invoice-level period_start/end (the canonical
	// service window for the invoice). Fall back to the first line's period
	// when the invoice-level fields are zero (rare; older Stripe payloads).
	periodStart, periodEnd := invoicePeriod(inv)

	// Tax: aggregate the per-tax_rate amounts when total_taxes is populated;
	// fall back to the legacy `tax` field for pre-2024 payloads.
	taxCents := invoiceTaxCents(inv)

	veloxInv := domain.Invoice{
		// CustomerID and SubscriptionID are populated by the driver.
		Status:             veloxStatus,
		PaymentStatus:      paymentStatus,
		Currency:           currency,
		SubtotalCents:      inv.Subtotal,
		TaxAmountCents:     taxCents,
		TotalAmountCents:   inv.Total,
		AmountDueCents:     inv.AmountDue,
		AmountPaidCents:    inv.AmountPaid,
		BillingPeriodStart: periodStart,
		BillingPeriodEnd:   periodEnd,
		BillingReason:      veloxBillingReason,
		StripeInvoiceID:    inv.ID,
		Footer:             strings.TrimSpace(inv.Footer),
		Memo:               strings.TrimSpace(inv.Description),
		// TaxStatus = ok: the imported invoice is finalized in Stripe so
		// tax (if any) was already calculated. Velox's tax pipeline does
		// not need to re-run.
		TaxStatus: domain.InvoiceTaxOK,
	}

	// status_transitions timestamps verbatim. issued_at = finalized_at, paid
	// and voided populate their respective columns. uncollectible reuses
	// voided_at because Velox lacks the dedicated uncollectible_at column;
	// the note above documents the conflation.
	if inv.StatusTransitions != nil {
		if inv.StatusTransitions.FinalizedAt > 0 {
			t := time.Unix(inv.StatusTransitions.FinalizedAt, 0).UTC()
			veloxInv.IssuedAt = &t
		}
		if inv.StatusTransitions.PaidAt > 0 {
			t := time.Unix(inv.StatusTransitions.PaidAt, 0).UTC()
			veloxInv.PaidAt = &t
		}
		if inv.StatusTransitions.VoidedAt > 0 {
			t := time.Unix(inv.StatusTransitions.VoidedAt, 0).UTC()
			veloxInv.VoidedAt = &t
		}
		if inv.StatusTransitions.MarkedUncollectibleAt > 0 && veloxInv.VoidedAt == nil {
			// Reuse voided_at for uncollectible-marked-at when no separate
			// voided_at exists. Already noted via statusNote.
			t := time.Unix(inv.StatusTransitions.MarkedUncollectibleAt, 0).UTC()
			veloxInv.VoidedAt = &t
		}
	}
	if inv.DueDate > 0 {
		t := time.Unix(inv.DueDate, 0).UTC()
		veloxInv.DueAt = &t
	}

	// Subscription resolution. Stripe v82 places the subscription on the
	// invoice's Parent.SubscriptionDetails; older / non-expanded payloads
	// surface it on the per-line `subscription` field (or its parent
	// SubscriptionItemDetails).
	subExternalID := extractSubscriptionExternalID(inv)

	// Line items: 1:1 mapping per Stripe lines.data[]. Description, quantity,
	// amount, period — all verbatim. Velox's line_type defaults to base_fee
	// for imported lines because the importer can't reliably classify them
	// (Stripe doesn't carry the same taxonomy); operators can post-process
	// individual rows.
	lineItems := make([]domain.InvoiceLineItem, 0, len(inv.Lines.Data))
	for i, line := range inv.Lines.Data {
		if line == nil {
			continue
		}
		li := mapInvoiceLineItem(line, currency)
		_ = i
		lineItems = append(lineItems, li)
	}

	// Lossy-field notes — surface to operators for post-import audit.
	if len(inv.Discounts) > 0 {
		notes = append(notes, fmt.Sprintf("stripe invoice has %d discount(s) — Velox coupons must be reapplied manually if you want to mirror them", len(inv.Discounts)))
	}
	if inv.AmountShipping > 0 {
		notes = append(notes, fmt.Sprintf("stripe invoice has amount_shipping=%d — Velox doesn't model shipping; the value is folded into total but no shipping line will exist", inv.AmountShipping))
	}
	if len(inv.DefaultTaxRates) > 0 {
		notes = append(notes, fmt.Sprintf("stripe invoice default_tax_rates (%d) ignored — Velox tax handling is per-tenant via the configured tax provider", len(inv.DefaultTaxRates)))
	}
	if len(inv.TotalTaxes) > 1 {
		notes = append(notes, fmt.Sprintf("stripe invoice has %d tax-rate splits — only the aggregate tax_amount_cents is preserved; per-rate breakdown is not modelled", len(inv.TotalTaxes)))
	}

	return MappedInvoice{
		Invoice:                veloxInv,
		LineItems:              lineItems,
		CustomerExternalID:     inv.Customer.ID,
		SubscriptionExternalID: subExternalID,
		Notes:                  notes,
	}, nil
}

// mapInvoiceLineItem translates a Stripe invoice line into a Velox line item.
// The line is anchored to the parent invoice by InvoiceID in the driver after
// the invoice itself is created.
func mapInvoiceLineItem(line *stripe.InvoiceLineItem, currency string) domain.InvoiceLineItem {
	desc := strings.TrimSpace(line.Description)
	if desc == "" {
		// Velox requires a description; fall back to the line id for an
		// operator-recognisable handle.
		desc = line.ID
	}

	li := domain.InvoiceLineItem{
		// LineType base_fee is the safe default — imported lines come from
		// finalized invoices that have already been settled, and the
		// distinction between base_fee/usage/add_on is a Velox-internal
		// taxonomy that doesn't have a 1:1 Stripe mapping. Operators who
		// need finer classification can re-tag post-import.
		LineType:    domain.LineTypeBaseFee,
		Description: desc,
		Quantity:    line.Quantity,
		AmountCents: line.Amount,
		Currency:    currency,
		// TotalAmountCents = AmountCents + per-line tax. Stripe's `taxes`
		// array is not always populated; default to the line's amount when
		// no per-line tax is set, falling back to summing taxes when
		// available so the imported total reconciles with Stripe's total.
		TotalAmountCents: line.Amount + sumLineTaxAmounts(line),
		TaxAmountCents:   sumLineTaxAmounts(line),
	}

	if line.Quantity > 0 && line.Amount > 0 {
		// Derive unit amount when both fields are set. Stripe's
		// pricing.unit_amount_decimal is the canonical source but is a
		// floating-point string we'd have to parse; the integer division
		// is a stable approximation for whole-cent prices.
		li.UnitAmountCents = line.Amount / line.Quantity
	}

	if line.Period != nil {
		if line.Period.Start > 0 {
			t := time.Unix(line.Period.Start, 0).UTC()
			li.BillingPeriodStart = &t
		}
		if line.Period.End > 0 {
			t := time.Unix(line.Period.End, 0).UTC()
			li.BillingPeriodEnd = &t
		}
	}
	return li
}

// sumLineTaxAmounts adds up the per-line tax amounts. Stripe carries the
// tax breakdown on each line in v82+. Returns 0 when no tax info is set.
func sumLineTaxAmounts(line *stripe.InvoiceLineItem) int64 {
	var total int64
	for _, t := range line.Taxes {
		if t == nil {
			continue
		}
		total += t.Amount
	}
	return total
}

// invoicePeriod returns the canonical service window for the invoice.
// Prefers invoice-level period_start/period_end (the aggregate cover) and
// falls back to the first line's period when the invoice-level fields are
// zero (rare on older payloads). Both ends are returned as UTC.
func invoicePeriod(inv *stripe.Invoice) (time.Time, time.Time) {
	if inv.PeriodStart > 0 && inv.PeriodEnd > 0 {
		return time.Unix(inv.PeriodStart, 0).UTC(), time.Unix(inv.PeriodEnd, 0).UTC()
	}
	if inv.Lines != nil && len(inv.Lines.Data) > 0 {
		first := inv.Lines.Data[0]
		if first != nil && first.Period != nil &&
			first.Period.Start > 0 && first.Period.End > 0 {
			return time.Unix(first.Period.Start, 0).UTC(),
				time.Unix(first.Period.End, 0).UTC()
		}
	}
	// Last-resort fallback: created/finalized timestamps. Velox's
	// billing_period_start/end are NOT NULL columns, so we must populate
	// them with something — Stripe's created is always set on a finalized
	// invoice.
	created := time.Unix(inv.Created, 0).UTC()
	return created, created
}

// invoiceTaxCents extracts the aggregate tax amount in cents. Prefers
// total_taxes (v82's per-rate breakdown) and falls back to the deprecated
// tax field for older payloads. Returns 0 when no tax was charged.
func invoiceTaxCents(inv *stripe.Invoice) int64 {
	if len(inv.TotalTaxes) > 0 {
		var total int64
		for _, t := range inv.TotalTaxes {
			if t == nil {
				continue
			}
			total += t.Amount
		}
		return total
	}
	// total - subtotal is the canonical Stripe-side tax derivation when
	// total_taxes is unset (legacy payloads). Defensive — never returns
	// negative.
	if inv.Total > inv.Subtotal {
		return inv.Total - inv.Subtotal
	}
	return 0
}

// extractSubscriptionExternalID navigates Stripe's nested subscription
// references. Order of preference:
//  1. invoice.parent.subscription_details.subscription (v82 canonical)
//  2. lines[0].subscription (object form, when expanded)
//  3. lines[0].parent.subscription_item_details.subscription (id form)
//  4. lines[0].parent.invoice_item_details.subscription (id form)
//
// Returns "" when none are populated (e.g. manual one-off invoices).
func extractSubscriptionExternalID(inv *stripe.Invoice) string {
	if inv.Parent != nil &&
		inv.Parent.SubscriptionDetails != nil &&
		inv.Parent.SubscriptionDetails.Subscription != nil &&
		strings.TrimSpace(inv.Parent.SubscriptionDetails.Subscription.ID) != "" {
		return inv.Parent.SubscriptionDetails.Subscription.ID
	}
	if inv.Lines == nil {
		return ""
	}
	for _, line := range inv.Lines.Data {
		if line == nil {
			continue
		}
		if line.Subscription != nil && strings.TrimSpace(line.Subscription.ID) != "" {
			return line.Subscription.ID
		}
		if line.Parent != nil {
			if line.Parent.SubscriptionItemDetails != nil &&
				strings.TrimSpace(line.Parent.SubscriptionItemDetails.Subscription) != "" {
				return line.Parent.SubscriptionItemDetails.Subscription
			}
			if line.Parent.InvoiceItemDetails != nil &&
				strings.TrimSpace(line.Parent.InvoiceItemDetails.Subscription) != "" {
				return line.Parent.InvoiceItemDetails.Subscription
			}
		}
	}
	return ""
}

// mapInvoiceStatus translates Stripe's invoice status onto Velox's pair of
// (InvoiceStatus, InvoicePaymentStatus). Returns sentinel
// ErrInvoiceUnsupportedStatus for draft / open invoices so the driver can
// emit a clear error CSV row instead of forcing a wrong mapping.
func mapInvoiceStatus(s stripe.InvoiceStatus) (domain.InvoiceStatus, domain.InvoicePaymentStatus, string, error) {
	switch s {
	case stripe.InvoiceStatusPaid:
		return domain.InvoicePaid, domain.PaymentSucceeded, "", nil
	case stripe.InvoiceStatusVoid:
		// Velox doesn't have a payment_status=void; failed is the closest
		// terminal state. The invoice-level status carries the void
		// signal authoritatively.
		return domain.InvoiceVoided, domain.PaymentFailed, "", nil
	case stripe.InvoiceStatusUncollectible:
		// Velox has no uncollectible status; voided is the closest match.
		// Note preserved so the audit trail keeps the Stripe distinction.
		return domain.InvoiceVoided, domain.PaymentFailed,
			"stripe status=uncollectible mapped to velox=voided (Velox lacks an uncollectible status; voided is the closest terminal state)", nil
	case stripe.InvoiceStatusDraft, stripe.InvoiceStatusOpen:
		return "", "", "", ErrInvoiceUnsupportedStatus
	default:
		return "", "", "", fmt.Errorf("unknown stripe invoice status %q", s)
	}
}

// mapInvoiceBillingReason translates Stripe's billing_reason onto Velox's
// narrower enum. Returns the Velox reason and an optional note describing
// any non-trivial mapping.
func mapInvoiceBillingReason(r stripe.InvoiceBillingReason) (domain.InvoiceBillingReason, string) {
	switch r {
	case stripe.InvoiceBillingReasonSubscriptionCreate:
		return domain.BillingReasonSubscriptionCreate, ""
	case stripe.InvoiceBillingReasonSubscriptionCycle:
		return domain.BillingReasonSubscriptionCycle, ""
	case stripe.InvoiceBillingReasonSubscriptionThreshold:
		return domain.BillingReasonThreshold, ""
	case stripe.InvoiceBillingReasonManual:
		return domain.BillingReasonManual, ""
	case stripe.InvoiceBillingReasonSubscriptionUpdate:
		return domain.BillingReasonManual,
			"stripe billing_reason=subscription_update mapped to velox=manual (Velox doesn't model the update reason; manual is the most accurate fallback for a proration / mid-cycle change-driven invoice)"
	case stripe.InvoiceBillingReasonSubscription:
		return domain.BillingReasonSubscriptionCycle,
			"stripe billing_reason=subscription (legacy pre-2018) mapped to velox=subscription_cycle"
	case stripe.InvoiceBillingReasonQuoteAccept:
		return domain.BillingReasonManual,
			"stripe billing_reason=quote_accept mapped to velox=manual (Velox doesn't model quotes)"
	case stripe.InvoiceBillingReasonAutomaticPendingInvoiceItemInvoice:
		return domain.BillingReasonManual,
			"stripe billing_reason=automatic_pending_invoice_item_invoice mapped to velox=manual"
	case stripe.InvoiceBillingReasonUpcoming:
		return domain.BillingReasonManual,
			"stripe billing_reason=upcoming mapped to velox=manual (upcoming is a preview state in Stripe; Velox treats imported as standalone)"
	case "":
		return domain.BillingReasonManual,
			"stripe invoice has empty billing_reason; defaulted to velox=manual"
	default:
		return domain.BillingReasonManual,
			fmt.Sprintf("unknown stripe billing_reason %q mapped to velox=manual", r)
	}
}
