package invoice

import (
	"bytes"
	"fmt"
	"time"

	"github.com/go-pdf/fpdf"

	"github.com/sagarsuperuser/velox/internal/domain"
)

// RenderPDF generates a professional PDF invoice and returns the bytes.
func RenderPDF(inv domain.Invoice, lineItems []domain.InvoiceLineItem, customerName string) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)
	pdf.AddPage()

	// Header
	pdf.SetFont("Helvetica", "B", 24)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(0, 12, "VELOX", "", 1, "L", false, 0, "")

	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5, "Usage-Based Billing Platform", "", 1, "L", false, 0, "")
	pdf.Ln(8)

	// Invoice info box
	pdf.SetFont("Helvetica", "B", 14)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(0, 8, "INVOICE", "", 1, "L", false, 0, "")
	pdf.Ln(2)

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(60, 60, 60)
	infoRow(pdf, "Invoice Number", inv.InvoiceNumber)
	infoRow(pdf, "Customer", customerName)
	infoRow(pdf, "Currency", inv.Currency)
	infoRow(pdf, "Status", string(inv.Status))

	if inv.IssuedAt != nil {
		infoRow(pdf, "Issued", inv.IssuedAt.Format("January 2, 2006"))
	}
	if inv.DueAt != nil {
		infoRow(pdf, "Due", inv.DueAt.Format("January 2, 2006"))
	}

	infoRow(pdf, "Billing Period",
		fmt.Sprintf("%s - %s",
			inv.BillingPeriodStart.Format("Jan 2, 2006"),
			inv.BillingPeriodEnd.Format("Jan 2, 2006")))

	pdf.Ln(8)

	// Line items table header
	pdf.SetFillColor(245, 245, 245)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(80, 80, 80)

	colWidths := []float64{75, 30, 30, 25, 30}
	headers := []string{"Description", "Quantity", "Unit Price", "Tax", "Amount"}
	for i, h := range headers {
		align := "L"
		if i > 0 {
			align = "R"
		}
		pdf.CellFormat(colWidths[i], 8, h, "", 0, align, true, 0, "")
	}
	pdf.Ln(-1)

	// Line items
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(40, 40, 40)

	for _, item := range lineItems {
		pdf.CellFormat(colWidths[0], 7, truncate(item.Description, 40), "", 0, "L", false, 0, "")
		pdf.CellFormat(colWidths[1], 7, formatQuantity(item.Quantity, item.LineType), "", 0, "R", false, 0, "")
		pdf.CellFormat(colWidths[2], 7, formatCents(item.UnitAmountCents), "", 0, "R", false, 0, "")
		pdf.CellFormat(colWidths[3], 7, formatCents(item.TaxAmountCents), "", 0, "R", false, 0, "")
		pdf.CellFormat(colWidths[4], 7, formatCents(item.TotalAmountCents), "", 0, "R", false, 0, "")
		pdf.Ln(-1)
	}

	// Separator
	pdf.Ln(2)
	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(10, pdf.GetY(), 200, pdf.GetY())
	pdf.Ln(4)

	// Totals
	totalsX := 130.0
	pdf.SetFont("Helvetica", "", 10)
	totalRow(pdf, totalsX, "Subtotal", formatCents(inv.SubtotalCents))
	if inv.DiscountCents > 0 {
		totalRow(pdf, totalsX, "Discount", "-"+formatCents(inv.DiscountCents))
	}
	if inv.TaxAmountCents > 0 {
		totalRow(pdf, totalsX, "Tax", formatCents(inv.TaxAmountCents))
	}

	pdf.Ln(2)
	pdf.SetFont("Helvetica", "B", 12)
	totalRow(pdf, totalsX, "Total Due", formatCents(inv.AmountDueCents))

	// Payment status
	pdf.Ln(8)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(120, 120, 120)
	if inv.PaymentStatus == domain.PaymentSucceeded && inv.PaidAt != nil {
		pdf.CellFormat(0, 5, fmt.Sprintf("Paid on %s", inv.PaidAt.Format("January 2, 2006")), "", 1, "L", false, 0, "")
	} else {
		pdf.CellFormat(0, 5, fmt.Sprintf("Payment Terms: Net %d days", inv.NetPaymentTermDays), "", 1, "L", false, 0, "")
	}

	if inv.Memo != "" {
		pdf.Ln(4)
		pdf.SetFont("Helvetica", "I", 9)
		pdf.MultiCell(0, 5, inv.Memo, "", "L", false)
	}

	// Footer
	pdf.Ln(10)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetTextColor(160, 160, 160)
	pdf.CellFormat(0, 4, fmt.Sprintf("Generated by Velox on %s", time.Now().UTC().Format("2006-01-02 15:04 UTC")), "", 1, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("render pdf: %w", err)
	}
	return buf.Bytes(), nil
}

func infoRow(pdf *fpdf.Fpdf, label, value string) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(40, 6, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.CellFormat(0, 6, value, "", 1, "L", false, 0, "")
}

func totalRow(pdf *fpdf.Fpdf, x float64, label, value string) {
	pdf.SetX(x)
	pdf.CellFormat(40, 7, label, "", 0, "L", false, 0, "")
	pdf.CellFormat(30, 7, value, "", 1, "R", false, 0, "")
}

func formatCents(cents int64) string {
	if cents == 0 {
		return "$0.00"
	}
	sign := ""
	if cents < 0 {
		sign = "-"
		cents = -cents
	}
	return fmt.Sprintf("%s$%d.%02d", sign, cents/100, cents%100)
}

func formatQuantity(qty int64, lineType domain.InvoiceLineItemType) string {
	if lineType == domain.LineTypeBaseFee {
		return "1"
	}
	return fmt.Sprintf("%d", qty)
}

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max-3] + "..."
}
