/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create customer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        external_id: string;
                        display_name: string;
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description Customer created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Customer"];
                    };
                };
                /** @description Customer already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meters */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Meter list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create meter */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        key: string;
                        name: string;
                        /** @default unit */
                        unit?: string;
                        /**
                         * @default sum
                         * @enum {string}
                         */
                        aggregation?: "sum" | "count" | "max" | "last";
                        rating_rule_version_id?: string;
                    };
                };
            };
            responses: {
                /** @description Meter created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List plans */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create plan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        name: string;
                        currency: string;
                        /** @enum {string} */
                        billing_interval: "monthly" | "yearly";
                        base_amount_cents?: number;
                        meter_ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Plan created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rating-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rating rules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rating rule list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create rating rule */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rule_key: string;
                        name: string;
                        /** @enum {string} */
                        mode: "flat" | "graduated" | "package";
                        currency: string;
                        flat_amount_cents?: number;
                        graduated_tiers?: {
                            up_to?: number;
                            unit_amount_cents?: number;
                        }[];
                        package_size?: number;
                        package_amount_cents?: number;
                    };
                };
            };
            responses: {
                /** @description Rating rule created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscription list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        display_name: string;
                        customer_id: string;
                        plan_id: string;
                        /**
                         * @default calendar
                         * @enum {string}
                         */
                        billing_time?: "calendar" | "anniversary";
                        trial_days?: number;
                        start_now?: boolean;
                    };
                };
            };
            responses: {
                /** @description Subscription created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate draft subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscription activated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/change-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change subscription plan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        new_plan_id: string;
                        immediate?: boolean;
                    };
                };
            };
            responses: {
                /** @description Plan changed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List usage events */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Ingest usage event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customer_id: string;
                        meter_id: string;
                        subscription_id?: string;
                        /** Format: int64 */
                        quantity: number;
                        properties?: Record<string, never>;
                        idempotency_key?: string;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            responses: {
                /** @description Event ingested */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage-events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch ingest usage events (max 1000) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customer_id: string;
                        meter_id: string;
                        quantity: number;
                    }[];
                };
            };
            responses: {
                /** @description All events ingested */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Partial success */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invoices */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/create_preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview the next invoice for a customer (Stripe-equivalent)
         * @description Answers "what is my next bill going to look like?" using the same
         *     line-set the cycle scan would emit if billing fired right now —
         *     so dashboard projected-bill matches the eventual finalized
         *     invoice. Composes across customer / subscription / pricing;
         *     registered as a sibling of `/v1/invoices` (chi picks the more
         *     specific pattern, otherwise `/{id}` would capture
         *     `create_preview` as an invoice ID). See
         *     [`docs/design-create-preview.md`](../docs/design-create-preview.md).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Customer to preview the invoice for. */
                        customer_id: string;
                        /**
                         * @description Optional. Defaults to the customer's primary active
                         *     subscription if not supplied.
                         */
                        subscription_id?: string;
                        /**
                         * @description Optional explicit window. Both bounds must be
                         *     supplied together; partial windows are rejected.
                         *     Defaults to the resolved subscription's current
                         *     cycle.
                         */
                        period?: {
                            /** Format: date-time */
                            from: string;
                            /** Format: date-time */
                            to: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Preview result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Customer or subscription not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Validation error (missing customer_id, partial period, no active sub, ...) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invoice with line items */
        get: operations["getInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download invoice PDF */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize draft invoice */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice finalized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger billing cycle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Billing cycle result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            invoices_generated?: number;
                            errors?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/preview/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invoice preview (dry run) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    subscription_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant credits to customer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customer_id: string;
                        /** Format: int64 */
                        amount_cents: number;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Credits granted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits/balance/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer credit balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customer_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Credit balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreditBalance"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dunning/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dunning policy */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dunning policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Configure dunning policy */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        enabled?: boolean;
                        retry_schedule?: string[];
                        max_retry_attempts?: number;
                        /** @enum {string} */
                        final_action?: "manual_review" | "pause" | "write_off_later";
                    };
                };
            };
            responses: {
                /** @description Policy updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook receiver
         * @description Receives Stripe webhook events. Verified via Stripe-Signature header.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event processed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: {
                /** @enum {string} */
                type?: "invalid_request_error" | "authentication_error" | "rate_limit_error" | "api_error";
                code?: string;
                message?: string;
                request_id?: string;
            };
        };
        Customer: {
            /** @example vlx_cus_42014438d82ddf33 */
            id?: string;
            external_id?: string;
            display_name?: string;
            email?: string;
            /** @enum {string} */
            status?: "active" | "archived";
            /** Format: date-time */
            created_at?: string;
        };
        Meter: {
            id?: string;
            key?: string;
            name?: string;
            unit?: string;
            /** @enum {string} */
            aggregation?: "sum" | "count" | "max" | "last";
            rating_rule_version_id?: string;
        };
        Plan: {
            id?: string;
            code?: string;
            name?: string;
            currency?: string;
            /** @enum {string} */
            billing_interval?: "monthly" | "yearly";
            /** @enum {string} */
            status?: "draft" | "active" | "archived";
            /** Format: int64 */
            base_amount_cents?: number;
            meter_ids?: string[];
        };
        RatingRule: {
            id?: string;
            rule_key?: string;
            name?: string;
            version?: number;
            /** @enum {string} */
            mode?: "flat" | "graduated" | "package";
            currency?: string;
            /** Format: int64 */
            flat_amount_cents?: number;
            graduated_tiers?: {
                up_to?: number;
                unit_amount_cents?: number;
            }[];
        };
        Subscription: {
            id?: string;
            code?: string;
            display_name?: string;
            customer_id?: string;
            plan_id?: string;
            /** @enum {string} */
            status?: "draft" | "active" | "paused" | "canceled" | "archived";
            /** @enum {string} */
            billing_time?: "calendar" | "anniversary";
            /** Format: date-time */
            trial_start_at?: string;
            /** Format: date-time */
            trial_end_at?: string;
        };
        UsageEvent: {
            id?: string;
            customer_id?: string;
            meter_id?: string;
            /** Format: int64 */
            quantity?: number;
            properties?: Record<string, never>;
            idempotency_key?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        /**
         * @description Lifecycle state of the invoice.
         * @enum {string}
         */
        InvoiceStatus: "draft" | "finalized" | "paid" | "voided";
        /**
         * @description Payment-attempt status. `unknown` marks a Stripe charge attempt that
         *     returned an ambiguous error (5xx, timeout, connection reset) where
         *     we cannot tell whether Stripe processed the charge — a reconciler
         *     resolves these by querying Stripe after a cool-off window.
         * @enum {string}
         */
        InvoicePaymentStatus: "pending" | "processing" | "succeeded" | "failed" | "unknown";
        /**
         * @description Whether tax has been successfully calculated. Happy path is `ok`.
         *     `pending` means a transient calculation failure is awaiting retry;
         *     `failed` means retries are exhausted (operator resolves manually).
         *     Pending/failed invoices are blocked from finalize so we never send
         *     a wrong tax amount.
         * @enum {string}
         */
        InvoiceTaxStatus: "ok" | "pending" | "failed";
        /**
         * @description Mirrors Stripe's `invoice.billing_reason`. Classifies the trigger
         *     that produced the invoice. Stamped at create time and never mutated.
         * @enum {string}
         */
        InvoiceBillingReason: "subscription_cycle" | "subscription_create" | "manual" | "threshold";
        /** @enum {string} */
        InvoiceLineType: "base_fee" | "usage" | "add_on" | "discount" | "tax";
        /**
         * @description Classifies per-item proration artifacts so the dedup index can
         *     distinguish a plan-change and a quantity-change that happen to
         *     share the same `(subscription, item, timestamp)`.
         * @enum {string}
         */
        ItemChangeType: "plan" | "quantity" | "add" | "remove";
        /**
         * @description A Velox invoice. Returned from create, finalize, void, list, get,
         *     apply-coupon, rotate-public-token, and collect-payment endpoints.
         */
        Invoice: {
            /** @example vlx_inv_42014438d82ddf33 */
            id: string;
            /**
             * @description Owning tenant. Returned for diagnostic clarity but redundant
             *     with the API key (which already determines the tenant).
             *     Omitted when empty.
             */
            tenant_id?: string;
            customer_id: string;
            /** @description Empty for one-off invoices not tied to a subscription. */
            subscription_id: string;
            /** @description Empty until the invoice is finalized. */
            invoice_number: string;
            status: components["schemas"]["InvoiceStatus"];
            payment_status: components["schemas"]["InvoicePaymentStatus"];
            /** @example USD */
            currency: string;
            /** Format: int64 */
            subtotal_cents: number;
            /** Format: int64 */
            discount_cents: number;
            /** Format: int64 */
            tax_amount_cents: number;
            /**
             * Format: int64
             * @description Tax rate in basis points (1850 = 18.50%).
             */
            tax_rate_bp: number;
            tax_name?: string;
            tax_country?: string;
            tax_id?: string;
            /**
             * @description Durable audit snapshot of the upstream tax engine that ran the
             *     calculation (e.g. `stripe`, `none`, `manual`).
             */
            tax_provider?: string;
            /**
             * @description Provider-side calculation reference captured at build time.
             *     For Stripe Tax this expires after 24 h; persisted so finalized
             *     invoices remain reconstructable past expiry.
             */
            tax_calculation_id?: string;
            /**
             * @description Provider-side committed transaction reference, captured at
             *     finalize. For Stripe Tax this is `tx_xxx` and is the handle
             *     the provider needs for a later reversal when a credit note is
             *     issued.
             */
            tax_transaction_id?: string;
            tax_reverse_charge?: boolean;
            tax_exempt_reason?: string;
            tax_status?: components["schemas"]["InvoiceTaxStatus"];
            /** Format: date-time */
            tax_deferred_at?: string | null;
            tax_retry_count?: number;
            tax_pending_reason?: string;
            /** Format: int64 */
            total_amount_cents: number;
            /** Format: int64 */
            amount_due_cents: number;
            /** Format: int64 */
            amount_paid_cents: number;
            /** Format: int64 */
            credits_applied_cents: number;
            /** Format: date-time */
            billing_period_start: string;
            /** Format: date-time */
            billing_period_end: string;
            /**
             * Format: date-time
             * @description Set when the invoice transitions out of draft.
             */
            issued_at?: string | null;
            /** Format: date-time */
            due_at?: string | null;
            /** Format: date-time */
            paid_at?: string | null;
            /** Format: date-time */
            voided_at?: string | null;
            stripe_payment_intent_id?: string;
            last_payment_error?: string;
            payment_overdue: boolean;
            auto_charge_pending?: boolean;
            /**
             * @description Hosted-invoice-URL credential (Stripe-parity
             *     `hosted_invoice_url`). Generated at finalize; drafts have an
             *     empty token. Rotatable via `POST
             *     /v1/invoices/{id}/rotate-public-token`.
             */
            public_token?: string;
            net_payment_term_days: number;
            memo?: string;
            footer?: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            source_plan_changed_at?: string | null;
            source_subscription_item_id?: string;
            source_change_type?: components["schemas"]["ItemChangeType"];
            billing_reason?: components["schemas"]["InvoiceBillingReason"];
            /**
             * @description Source Stripe invoice id (`in_xxx`) populated by `velox-import`
             *     for invoices imported from a Stripe account. Empty for
             *     Velox-native invoices.
             */
            stripe_invoice_id?: string;
        };
        /** @description A single line on an invoice. */
        InvoiceLineItem: {
            id: string;
            invoice_id: string;
            /** @description Owning tenant. Omitted when empty. */
            tenant_id?: string;
            line_type: components["schemas"]["InvoiceLineType"];
            meter_id?: string;
            description: string;
            /** Format: int64 */
            quantity: number;
            /** Format: int64 */
            unit_amount_cents: number;
            /** Format: int64 */
            amount_cents: number;
            /** Format: int64 */
            tax_rate_bp: number;
            /** Format: int64 */
            tax_amount_cents: number;
            tax_jurisdiction?: string;
            tax_code?: string;
            /**
             * @description Stripe-canonical structured `taxability_reason`
             *     (`standard_rated`, `reverse_charge`, `not_collecting`,
             *     `customer_exempt`, `product_exempt`, `zero_rated`, etc.).
             *     Empty for non-Stripe providers.
             */
            tax_reason?: string;
            /** Format: int64 */
            total_amount_cents: number;
            currency: string;
            pricing_mode?: string;
            rating_rule_version_id?: string;
            /** Format: date-time */
            billing_period_start?: string | null;
            /** Format: date-time */
            billing_period_end?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Response shape for `GET /v1/invoices/{id}`. The handler returns the
         *     invoice and its line items as separate top-level keys (rather than
         *     nesting `line_items` inside the invoice) so the client can render
         *     the two arrays independently.
         */
        InvoiceWithLineItems: {
            invoice: components["schemas"]["Invoice"];
            line_items: components["schemas"]["InvoiceLineItem"][];
        };
        CreditBalance: {
            customer_id?: string;
            /** Format: int64 */
            balance_cents?: number;
            /** Format: int64 */
            total_granted?: number;
            /** Format: int64 */
            total_used?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice with its line items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceWithLineItems"];
                };
            };
            /** @description Invoice not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
