/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    /** @description Exact-match filter on the caller-assigned external ID. */
                    external_id?: string;
                    /** @description Comma-separated customer IDs to fetch exactly. */
                    ids?: string;
                    /**
                     * @description Case-insensitive substring match on display name, email,
                     *     external ID, or ID. Matching runs post-decryption (PII
                     *     columns are encrypted at rest), bounded to the first 5000
                     *     rows of the tenant's filtered set.
                     */
                    search?: string;
                    /** @description One of display_name, email, external_id, status, created_at (default). */
                    sort?: string;
                    dir?: "asc" | "desc";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create customer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        external_id: string;
                        display_name: string;
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description Customer created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Customer"];
                    };
                };
                /** @description Customer already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{id}/rotate-cost-dashboard-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the public cost-dashboard token (ADR-031)
         * @description Mints a fresh `vlx_pcd_…` token and writes it to the customer
         *     row. The previous token is invalidated immediately (read-only
         *     public surface; no grace window). The plaintext token is the
         *     sole credential for `GET /v1/public/cost-dashboard/{token}`
         *     and is shown ONCE — Velox never returns it again after this
         *     response. Audit log records the rotation without the token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rotated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example vlx_pcd_a3f9c4... */
                            token: string;
                            /** @example https://api.velox.dev/v1/public/cost-dashboard/vlx_pcd_a3f9c4... */
                            public_url: string;
                        };
                    };
                };
                /** @description Customer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/cost-dashboard/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public cost-dashboard projection (ADR-031)
         * @description Unauthenticated. The `vlx_pcd_…` token in the URL is the sole
         *     credential — partners embed via iframe / fetch from their own
         *     app without an API key. Sanitized projection: customer_id,
         *     tenant_id, billing_period, subscriptions, usage[], totals,
         *     projected_total_cents. PII (email, display_name, external_id,
         *     metadata, billing_profile) is NEVER on this response. Wrong
         *     prefix or unknown token → 401 (anti-enumeration). No active
         *     sub → 200 with `billing_period.source = "no_subscription"`
         *     and empty arrays.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Projection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limited (60/min/IP) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meters */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Meter list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create meter */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        key: string;
                        name: string;
                        /** @default unit */
                        unit?: string;
                        /**
                         * @default sum
                         * @enum {string}
                         */
                        aggregation?: "sum" | "count" | "max" | "last";
                        rating_rule_version_id?: string;
                    };
                };
            };
            responses: {
                /** @description Meter created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List plans */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create plan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        name: string;
                        currency: string;
                        /** @enum {string} */
                        billing_interval: "monthly" | "yearly";
                        base_amount_cents?: number;
                        /**
                         * @description Optional. Defaults to in_arrears. See Plan.base_bill_timing
                         *     for semantics (ADR-031).
                         * @enum {string}
                         */
                        base_bill_timing?: "in_advance" | "in_arrears";
                        meter_ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Plan created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rating-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rating rules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rating rule list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create rating rule */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rule_key: string;
                        name: string;
                        /** @enum {string} */
                        mode: "flat" | "graduated" | "package";
                        currency: string;
                        /** @description Per-unit rate in cents, as a decimal string (e.g. "0.0003" = $3.00 per 1,000,000 units). */
                        flat_amount_cents?: string;
                        graduated_tiers?: {
                            up_to?: number;
                            /** @description Per-unit rate in cents, as a decimal string. */
                            unit_amount_cents?: string;
                        }[];
                        package_size?: number;
                        package_amount_cents?: number;
                        /** @description Package-mode per-unit overage rate in cents, as a decimal string. Fixed fees (package_amount_cents) stay integer cents. */
                        overage_unit_amount_cents?: string;
                    };
                };
            };
            responses: {
                /** @description Rating rule created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions */
        get: {
            parameters: {
                query?: {
                    customer_id?: string;
                    /** @description Filter to subscriptions with a live item on this plan. */
                    plan_id?: string;
                    status?: string;
                    /** @description Case-insensitive substring match on display name or code. */
                    search?: string;
                    /** @description One of display_name, status, next_billing_at, trial_end_at, created_at (default). */
                    sort?: string;
                    dir?: "asc" | "desc";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscription list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        display_name: string;
                        customer_id: string;
                        plan_id: string;
                        /**
                         * @default calendar
                         * @enum {string}
                         */
                        billing_time?: "calendar" | "anniversary";
                        trial_days?: number;
                        start_now?: boolean;
                    };
                };
            };
            responses: {
                /** @description Subscription created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate draft subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscription activated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List usage events */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Ingest usage event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customer_id: string;
                        meter_id: string;
                        subscription_id?: string;
                        /** Format: int64 */
                        quantity: number;
                        properties?: Record<string, never>;
                        idempotency_key?: string;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            responses: {
                /** @description Event ingested */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage-events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch ingest usage events (max 1000) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customer_id: string;
                        meter_id: string;
                        quantity: number;
                    }[];
                };
            };
            responses: {
                /** @description All events ingested */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Partial success */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invoices */
        get: {
            parameters: {
                query?: {
                    customer_id?: string;
                    subscription_id?: string;
                    status?: string;
                    payment_status?: string;
                    /** @description Case-insensitive substring match on invoice number. */
                    search?: string;
                    /**
                     * @description Lower bound on created_at, inclusive. RFC3339 instant or
                     *     bare YYYY-MM-DD (anchored at 00:00:00Z).
                     */
                    from?: string;
                    /**
                     * @description Upper bound on created_at, inclusive. RFC3339 instant or
                     *     bare YYYY-MM-DD (anchored at 23:59:59Z).
                     */
                    to?: string;
                    /**
                     * @description When true, restrict to open invoices past their due date
                     *     that haven't settled (finalized + due_at < now +
                     *     payment_status not succeeded/processing). Backs the
                     *     dashboard's "Past due" segment.
                     */
                    overdue?: boolean;
                    /** @description Comma-separated invoice IDs to fetch exactly. */
                    ids?: string;
                    /** @description One of invoice_number, amount_due_cents, billing_period_start, due_at, issued_at, status, payment_status, created_at (default). */
                    sort?: string;
                    dir?: "asc" | "desc";
                    limit?: number;
                    offset?: number;
                    /** @description Opaque cursor (default created_at sort only); takes precedence over offset. */
                    after?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/create_preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview the next invoice for a customer (Stripe-equivalent)
         * @description Answers "what is my next bill going to look like?" using the same
         *     line-set the cycle scan would emit if billing fired right now —
         *     so dashboard projected-bill matches the eventual finalized
         *     invoice. Composes across customer / subscription / pricing;
         *     registered as a sibling of `/v1/invoices` (chi picks the more
         *     specific pattern, otherwise `/{id}` would capture
         *     `create_preview` as an invoice ID). See
         *     [`docs/design-create-preview.md`](../docs/design-create-preview.md).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Customer to preview the invoice for. */
                        customer_id: string;
                        /**
                         * @description Optional. Defaults to the customer's primary active
                         *     subscription if not supplied.
                         */
                        subscription_id?: string;
                        /**
                         * @description Optional explicit window. Both bounds must be
                         *     supplied together; partial windows are rejected.
                         *     Defaults to the resolved subscription's current
                         *     cycle.
                         */
                        period?: {
                            /** Format: date-time */
                            from: string;
                            /** Format: date-time */
                            to: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Preview result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Customer or subscription not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Validation error (missing customer_id, partial period, no active sub, ...) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invoice with line items */
        get: operations["getInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download invoice PDF */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize draft invoice */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice finalized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{id}/retry-tax": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry tax calculation on a deferred invoice
         * @description Re-runs tax calculation against a draft invoice whose
         *     `tax_status` is `pending` or `failed`. Backs the operator-
         *     facing "Retry tax" action surfaced by the unified
         *     `Attention` shape.
         *
         *     Idempotent: each call increments `tax_retry_count` and
         *     rewrites the per-line and invoice-level tax fields. A retry
         *     that succeeds clears `tax_pending_reason` / `tax_error_code`
         *     and unblocks finalize. A retry that still fails writes the
         *     new typed code so the dashboard banner refreshes — operators
         *     get an immediate signal of whether their fix worked.
         *
         *     Returns the updated invoice (carrying the re-derived
         *     `attention`) on success or post-retry failure. A retry that
         *     is still failing is **not** an HTTP error — the caller
         *     renders the new attention.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice updated; check `attention` for the new state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invoice"];
                    };
                };
                /** @description Invoice not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /**
                 * @description Invoice is not in a retryable state (status != draft, or
                 *     tax_status not in pending/failed).
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password; mint an httpOnly session cookie
         * @description Validates email + password, mints a server-side session row, and
         *     sets `Set-Cookie: velox_session=...; HttpOnly; SameSite=Lax; Path=/`.
         *     Subsequent dashboard requests authenticate via the cookie; sessions
         *     are bound to `users.id` and are independent of API key lifecycle.
         *     See ADR-011.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Session minted; cookie set on response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user_id: string;
                            tenant_id: string;
                            email: string;
                            livemode: boolean;
                            /** Format: date-time */
                            expires_at: string;
                        };
                    };
                };
                /** @description Invalid email or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Account locked after too many failed attempts (15-min cooldown) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current session and clear the cookie
         * @description Marks the session row as revoked server-side and clears the
         *     cookie on the response. Idempotent — a missing or stale cookie
         *     is treated as already-logged-out.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch the dashboard session between test and live mode
         * @description Updates `dashboard_sessions.livemode` for the cookie session.
         *     All subsequent requests inherit the new mode via session middleware,
         *     so customers / invoices / subscriptions / API keys reads filter to
         *     the active mode without per-call mode parameters. The same operator
         *     flips back and forth without re-authenticating.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        livemode: boolean;
                    };
                };
            };
            responses: {
                /** @description Mode updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            livemode: boolean;
                        };
                    };
                };
                /** @description Missing or expired session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset link
         * @description Always returns 204 regardless of whether the email exists, to
         *     avoid account enumeration. If a user matches, a single-use 1-hour
         *     token is generated and the reset link is delivered out-of-band
         *     (SMTP delivery deferred — currently logged to stdout).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Request accepted (regardless of email existence) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password using a reset token
         * @description Consumes a single-use reset token and updates the user's password.
         *     The token is invalidated on use; reuse or expired tokens return 422.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Password updated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Token invalid/expired or password does not meet policy */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve the current credential to its tenant context
         * @description Returns the resolved auth context for whichever credential the
         *     request carries — `velox_session` cookie (dashboard) or
         *     `Authorization: Bearer` (SDK / curl). Cookie path returns
         *     `user_id` + `email`; Bearer path returns `key_id` + `key_type`.
         *     Both always return `tenant_id` + `livemode`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resolved auth context */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tenant_id: string;
                            livemode: boolean;
                            user_id?: string;
                            email?: string;
                            key_id?: string;
                            /** @enum {string} */
                            key_type?: "platform" | "secret" | "publishable";
                        };
                    };
                };
                /** @description Missing, revoked, or expired credential */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger billing cycle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Billing cycle result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            invoices_generated?: number;
                            errors?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/preview/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invoice preview (dry run) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    subscription_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant credits to customer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customer_id: string;
                        /** Format: int64 */
                        amount_cents: number;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Credits granted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits/balance/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer credit balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customer_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Credit balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreditBalance"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/test-clocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List test clocks for the active tenant
         * @description Test mode only — returns 403 in live mode. Test clocks let
         *     operators simulate time-bound billing flows without waiting for
         *     wall-clock advances. See ADR / docs for the simulator semantics.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Test clocks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: Record<string, never>[];
                        };
                    };
                };
                /** @description Caller is in live mode */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a test clock
         * @description Test mode only. The clock starts in `ready` state at
         *     `frozen_time`. Use `/advance` to move it forward.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /** Format: date-time */
                        frozen_time: string;
                    };
                };
            };
            responses: {
                /** @description Clock created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/test-clocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a test clock by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Clock */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Clock not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a test clock (cascades to pinned subscriptions) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Clock deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/test-clocks/{id}/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions pinned to this clock */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscriptions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: Record<string, never>[];
                        };
                    };
                };
                /** @description Clock not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/test-clocks/{id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance the clock to a new frozen_time
         * @description Moves the clock forward and synchronously runs billing catchup
         *     for every subscription pinned to this clock. While catchup runs,
         *     the clock is in `advancing` state and concurrent advances 409.
         *     Catchup failures flip the clock to `internal_failure` — operator
         *     must inspect and delete to unstick.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        frozen_time: string;
                    };
                };
            };
            responses: {
                /** @description Clock advanced */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Clock is not in `ready` state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description New frozen_time is not strictly after the current */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: {
                /** @enum {string} */
                type?: "invalid_request_error" | "authentication_error" | "rate_limit_error" | "api_error";
                code?: string;
                message?: string;
                request_id?: string;
            };
        };
        Customer: {
            /** @example vlx_cus_42014438d82ddf33 */
            id?: string;
            external_id?: string;
            display_name?: string;
            email?: string;
            /** @enum {string} */
            status?: "active" | "archived";
            /** Format: date-time */
            created_at?: string;
            /**
             * @description Test clock this customer is pinned to (test mode only). When set,
             *     the customer — and any invoices/subscriptions created for it —
             *     run on the clock's simulated time. Empty for live customers. The
             *     dashboard reads it to show the "test clock" badge + simulated-time
             *     banner on the customer and its invoices.
             */
            test_clock_id?: string;
        };
        Meter: {
            id?: string;
            key?: string;
            name?: string;
            unit?: string;
            /** @enum {string} */
            aggregation?: "sum" | "count" | "max" | "last";
            rating_rule_version_id?: string;
        };
        Plan: {
            id?: string;
            code?: string;
            name?: string;
            currency?: string;
            /** @enum {string} */
            billing_interval?: "monthly" | "yearly";
            /** @enum {string} */
            status?: "draft" | "active" | "archived";
            /** Format: int64 */
            base_amount_cents?: number;
            /**
             * @description When the recurring base fee is invoiced relative to the period it covers.
             *     in_arrears (default): base + usage billed at period end.
             *     in_advance: base billed at period start (day 1 on create; cycle-close invoice
             *     carries upcoming period's base + elapsed period's usage). Usage lines are
             *     always arrears regardless of this flag. See ADR-031.
             * @enum {string}
             */
            base_bill_timing?: "in_advance" | "in_arrears";
            meter_ids?: string[];
        };
        RatingRule: {
            id?: string;
            rule_key?: string;
            name?: string;
            version?: number;
            /** @enum {string} */
            mode?: "flat" | "graduated" | "package";
            currency?: string;
            /** @description Per-unit rate in cents, as a decimal string (e.g. "0.0003" = $3.00 per 1,000,000 units). Arbitrary precision; invoice line amounts and totals still round to whole cents. */
            flat_amount_cents?: string;
            graduated_tiers?: {
                up_to?: number;
                /** @description Per-unit rate in cents, as a decimal string (see flat_amount_cents). */
                unit_amount_cents?: string;
            }[];
        };
        Subscription: {
            id?: string;
            code?: string;
            display_name?: string;
            customer_id?: string;
            plan_id?: string;
            /** @enum {string} */
            status?: "draft" | "trialing" | "active" | "canceled" | "archived";
            /** @enum {string} */
            billing_time?: "calendar" | "anniversary";
            /** Format: date-time */
            trial_start_at?: string;
            /** Format: date-time */
            trial_end_at?: string;
        };
        UsageEvent: {
            id?: string;
            customer_id?: string;
            meter_id?: string;
            /** Format: int64 */
            quantity?: number;
            properties?: Record<string, never>;
            idempotency_key?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        /**
         * @description Lifecycle state of the invoice. `uncollectible` marks an invoice
         *     a dunning policy has given up collecting (no further retries) while
         *     keeping it on the books — distinct from `voided` (cancelled, owes
         *     nothing).
         * @enum {string}
         */
        InvoiceStatus: "draft" | "finalized" | "paid" | "voided" | "uncollectible";
        /**
         * @description Payment-attempt status. `unknown` marks a Stripe charge attempt that
         *     returned an ambiguous error (5xx, timeout, connection reset) where
         *     we cannot tell whether Stripe processed the charge — a reconciler
         *     resolves these by querying Stripe after a cool-off window.
         * @enum {string}
         */
        InvoicePaymentStatus: "pending" | "processing" | "succeeded" | "failed" | "unknown";
        /**
         * @description Whether tax has been successfully calculated. Happy path is `ok`.
         *     `pending` means a transient calculation failure is awaiting retry;
         *     `failed` means retries are exhausted (operator resolves manually).
         *     Pending/failed invoices are blocked from finalize so we never send
         *     a wrong tax amount.
         * @enum {string}
         */
        InvoiceTaxStatus: "ok" | "pending" | "failed";
        /**
         * @description Urgency of an Attention surface. Operators sort/filter on this
         *     and the dashboard renders one colour per level. Priority
         *     descending: Critical > Warning > Info.
         * @enum {string}
         */
        AttentionSeverity: "info" | "warning" | "critical";
        /**
         * @description Closed, typed code naming why an invoice needs operator
         *     attention. Stable public-API contract — codes are never
         *     repurposed; deprecations keep the code reserved and add a
         *     successor. See `Attention.code` for the open, provider-specific
         *     sub-code.
         * @enum {string}
         */
        AttentionReason: "tax_calculation_failed" | "tax_location_required" | "payment_failed" | "payment_unconfirmed" | "overdue" | "payment_processing" | "payment_scheduled" | "awaiting_payment" | "no_payment_method";
        /**
         * @description Operator's recommended next step. Closed enum because every
         *     code maps to a concrete server endpoint or frontend route,
         *     and audit logs key off the code.
         * @enum {string}
         */
        AttentionAction: "edit_billing_profile" | "retry_tax" | "retry_payment" | "wait_provider" | "rotate_api_key" | "reconcile_payment" | "review_registration" | "charge_now" | "send_reminder" | "add_payment_method" | "update_payment_method" | "connect_tax_provider";
        AttentionActionItem: {
            code: components["schemas"]["AttentionAction"];
            /**
             * @description Default rendering label. UIs are free to substitute
             *     localized copy.
             */
            label?: string;
        };
        /**
         * @description Unified "this invoice needs operator attention" surface.
         *     Computed server-side from durable invoice fields
         *     (`tax_status`, `tax_error_code`, `payment_status`,
         *     `last_payment_error`, `payment_overdue`). Never persisted —
         *     always derived. Omitted entirely when the invoice is healthy
         *     (matches Stripe's `last_finalization_error: null` ergonomic).
         *     See ADR-009.
         */
        Attention: {
            severity: components["schemas"]["AttentionSeverity"];
            reason: components["schemas"]["AttentionReason"];
            /** @description Human-readable headline copy, safe to render verbatim. */
            message: string;
            /**
             * @description Prescribed next steps. First item is the primary CTA; the
             *     rest are secondary.
             */
            actions?: components["schemas"]["AttentionActionItem"][];
            /**
             * @description Open, dotted, provider-specific code (e.g.
             *     `tax.customer_data_invalid`, `payment.declined`,
             *     `lifecycle.overdue`). New codes ship without a contract
             *     bump. Stripe parity.
             */
            code?: string;
            /**
             * @description Deep link to operator-facing documentation for this
             *     reason. Stripe parity.
             */
            doc_url?: string;
            /**
             * @description Dotted-path pointer at the entity field the operator must
             *     edit to resolve the issue (e.g.
             *     `customer.address.postal_code`). Stripe parity. Empty
             *     when the resolution isn't field-scoped.
             */
            param?: string;
            /**
             * @description Raw provider payload (Stripe Tax JSON envelope, last
             *     payment error message). Disclosed in a collapsible
             *     section for diagnostic depth.
             */
            detail?: string;
            /**
             * Format: date-time
             * @description When the attention condition started — operators triage
             *     by age. tax_deferred_at for tax reasons; due_at for
             *     overdue; updated_at as a proxy for payment failures.
             */
            since?: string;
        };
        /**
         * @description Mirrors Stripe's `invoice.billing_reason`. Classifies the trigger
         *     that produced the invoice. Stamped at create time and never mutated.
         * @enum {string}
         */
        InvoiceBillingReason: "subscription_cycle" | "subscription_create" | "subscription_cancel" | "subscription_update" | "manual" | "threshold";
        /** @enum {string} */
        InvoiceLineType: "base_fee" | "usage" | "add_on" | "discount" | "tax";
        /**
         * @description Classifies per-item proration artifacts so the dedup index can
         *     distinguish a plan-change and a quantity-change that happen to
         *     share the same `(subscription, item, timestamp)`.
         * @enum {string}
         */
        ItemChangeType: "plan" | "quantity" | "add" | "remove";
        /**
         * @description A Velox invoice. Returned from create, finalize, void, list, get,
         *     rotate-public-token, and collect-payment endpoints.
         */
        Invoice: {
            /** @example vlx_inv_42014438d82ddf33 */
            id: string;
            /**
             * @description Owning tenant. Returned for diagnostic clarity but redundant
             *     with the API key (which already determines the tenant).
             *     Omitted when empty.
             */
            tenant_id?: string;
            customer_id: string;
            /** @description Empty for one-off invoices not tied to a subscription. */
            subscription_id: string;
            /** @description Empty until the invoice is finalized. */
            invoice_number: string;
            status: components["schemas"]["InvoiceStatus"];
            payment_status: components["schemas"]["InvoicePaymentStatus"];
            /** @example USD */
            currency: string;
            /** Format: int64 */
            subtotal_cents: number;
            /** Format: int64 */
            discount_cents: number;
            /** Format: int64 */
            tax_amount_cents: number;
            /**
             * Format: double
             * @description Tax rate as a percent (18.50 = 18.50%), up to 4-decimal precision. ADR-042/043.
             */
            tax_rate: number;
            tax_name?: string;
            tax_country?: string;
            tax_id?: string;
            /**
             * @description Durable audit snapshot of the upstream tax engine that ran the
             *     calculation (e.g. `stripe`, `none`, `manual`).
             */
            tax_provider?: string;
            /**
             * @description Provider-side calculation reference captured at build time.
             *     For Stripe Tax this expires after 24 h; persisted so finalized
             *     invoices remain reconstructable past expiry.
             */
            tax_calculation_id?: string;
            /**
             * @description Provider-side committed transaction reference, captured at
             *     finalize. For Stripe Tax this is `tx_xxx` and is the handle
             *     the provider needs for a later reversal when a credit note is
             *     issued.
             */
            tax_transaction_id?: string;
            tax_reverse_charge?: boolean;
            tax_exempt_reason?: string;
            tax_status?: components["schemas"]["InvoiceTaxStatus"];
            /** Format: date-time */
            tax_deferred_at?: string | null;
            tax_retry_count?: number;
            tax_pending_reason?: string;
            /**
             * @description Typed taxonomy of `tax_pending_reason`. One of
             *     `customer_data_invalid`, `jurisdiction_unsupported`,
             *     `provider_outage`, `provider_auth`, `unknown`. Empty for
             *     invoices deferred before this column existed (migration
             *     0067).
             */
            tax_error_code?: string;
            attention?: components["schemas"]["Attention"];
            /** Format: int64 */
            total_amount_cents: number;
            /** Format: int64 */
            amount_due_cents: number;
            /** Format: int64 */
            amount_paid_cents: number;
            /** Format: int64 */
            credits_applied_cents: number;
            /** Format: date-time */
            billing_period_start: string;
            /** Format: date-time */
            billing_period_end: string;
            /** @description Human period string with the inclusive last covered day ("Jun 1, 2028 – Jun 30, 2028"), date-only in the tenant timezone (ADR-058). Computed on read; the raw billing_period_start/end stay half-open. Empty/omitted for one-off invoices with no period. */
            billing_period_display?: string;
            /**
             * Format: date-time
             * @description Set when the invoice transitions out of draft.
             */
            issued_at?: string | null;
            /** Format: date-time */
            due_at?: string | null;
            /** Format: date-time */
            paid_at?: string | null;
            /** Format: date-time */
            voided_at?: string | null;
            stripe_payment_intent_id?: string;
            last_payment_error?: string;
            payment_overdue: boolean;
            auto_charge_pending?: boolean;
            /**
             * @description Hosted-invoice-URL credential (Stripe-parity
             *     `hosted_invoice_url`). Generated at finalize; drafts have an
             *     empty token. Rotatable via `POST
             *     /v1/invoices/{id}/rotate-public-token`.
             */
            public_token?: string;
            net_payment_term_days: number;
            memo?: string;
            footer?: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            source_plan_changed_at?: string | null;
            source_subscription_item_id?: string;
            source_change_type?: components["schemas"]["ItemChangeType"];
            billing_reason?: components["schemas"]["InvoiceBillingReason"];
            /**
             * @description Source Stripe invoice id (`in_xxx`) populated by `velox-import`
             *     for invoices imported from a Stripe account. Empty for
             *     Velox-native invoices.
             */
            stripe_invoice_id?: string;
            /**
             * @description Whether this invoice's domain timestamps (created/issued/due/paid)
             *     were stamped on a test clock's simulated time rather than
             *     wall-clock. Captured at write time (engine: the subscription is
             *     clock-pinned; manual composer: the customer is clock-pinned). The
             *     dashboard renders a "simulated" badge from this authoritative flag
             *     instead of inferring it. Always false in live mode.
             */
            is_simulated?: boolean;
        };
        /** @description A single line on an invoice. */
        InvoiceLineItem: {
            id: string;
            invoice_id: string;
            /** @description Owning tenant. Omitted when empty. */
            tenant_id?: string;
            line_type: components["schemas"]["InvoiceLineType"];
            meter_id?: string;
            description: string;
            /** Format: int64 */
            quantity: number;
            /** @description Exact (possibly fractional) usage quantity as a decimal string (e.g. "1.5"). The integer `quantity` is this truncated, kept for back-compat (Stripe quantity_decimal parity). "0" means none — use `quantity`. Line amounts stay whole cents. */
            quantity_decimal?: string;
            /** Format: int64 */
            unit_amount_cents: number;
            /** @description Full-precision per-unit price in DECIMAL CENTS (e.g. "0.3" = $0.003 per unit), the Stripe unit_amount_decimal model. Derived on read as amount_cents ÷ quantity, so it reconciles with the rounded line amount and, unlike the whole-cent `unit_amount_cents`, never collapses a sub-cent rate to 0. Render with the decimal-aware rate formatter; line amounts/totals stay whole cents. */
            unit_amount_decimal?: string;
            /** Format: int64 */
            amount_cents: number;
            /**
             * Format: double
             * @description Tax rate as a percent (18.50 = 18.50%), up to 4-decimal precision. ADR-042/043.
             */
            tax_rate: number;
            /** Format: int64 */
            tax_amount_cents: number;
            tax_jurisdiction?: string;
            tax_code?: string;
            /**
             * @description Stripe-canonical structured `taxability_reason`
             *     (`standard_rated`, `reverse_charge`, `not_collecting`,
             *     `customer_exempt`, `product_exempt`, `zero_rated`, etc.).
             *     Empty for non-Stripe providers.
             */
            tax_reason?: string;
            /** Format: int64 */
            total_amount_cents: number;
            currency: string;
            pricing_mode?: string;
            rating_rule_version_id?: string;
            /** Format: date-time */
            billing_period_start?: string | null;
            /** Format: date-time */
            billing_period_end?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Response shape for `GET /v1/invoices/{id}`. The handler returns the
         *     invoice and its line items as separate top-level keys (rather than
         *     nesting `line_items` inside the invoice) so the client can render
         *     the two arrays independently.
         */
        InvoiceWithLineItems: {
            invoice: components["schemas"]["Invoice"];
            line_items: components["schemas"]["InvoiceLineItem"][];
        };
        CreditBalance: {
            customer_id?: string;
            /** Format: int64 */
            balance_cents?: number;
            /** Format: int64 */
            total_granted?: number;
            /** Format: int64 */
            total_used?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice with its line items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceWithLineItems"];
                };
            };
            /** @description Invoice not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
