package middleware

import (
	"net/http"
	"strconv"
	"time"

	chimw "github.com/go-chi/chi/v5/middleware"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	httpRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_http_requests_total",
			Help: "Total HTTP requests by method, path pattern, and status code.",
		},
		[]string{"method", "path", "status"},
	)

	httpRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "velox_http_request_duration_seconds",
			Help:    "HTTP request latency in seconds.",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
		},
		[]string{"method", "path", "status"},
	)

	httpRequestsInFlight = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "velox_http_requests_in_flight",
			Help: "Current number of HTTP requests being processed.",
		},
	)

	billingCyclesTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_billing_cycles_total",
			Help: "Total billing cycles executed.",
		},
	)

	invoicesGenerated = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_invoices_generated_total",
			Help: "Total invoices generated by the billing engine.",
		},
	)

	usageEventsIngested = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_usage_events_ingested_total",
			Help: "Total usage events ingested.",
		},
	)

	billingCycleDuration = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "velox_billing_cycle_duration_seconds",
			Help:    "Duration of billing cycle runs in seconds.",
			Buckets: []float64{0.1, 0.5, 1, 2.5, 5, 10, 30, 60, 120, 300},
		},
	)

	billingCycleErrors = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_billing_cycle_errors_total",
			Help: "Total billing cycle errors.",
		},
	)

	paymentCharges = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_payment_charges_total",
			Help: "Total payment charges by result.",
		},
		[]string{"result"},
	)

	webhookDeliveries = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_webhook_deliveries_total",
			Help: "Total outbound webhook deliveries by status.",
		},
		[]string{"status"},
	)

	dunningRunsProcessed = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_dunning_runs_processed_total",
			Help: "Total dunning runs processed.",
		},
	)

	creditOperations = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_credit_operations_total",
			Help: "Total credit operations by type.",
		},
		[]string{"type"},
	)

	autoChargeRetries = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_auto_charge_retries_total",
			Help: "Total auto-charge retries by result.",
		},
		[]string{"result"},
	)

	auditWriteErrors *prometheus.CounterVec

	stripeBreakerState = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "velox_stripe_breaker_state",
			Help: "Global circuit breaker state for Stripe calls. 0=closed, 1=half_open, 2=open.",
		},
	)

	scheduledCleanupRows = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_scheduled_cleanup_rows_total",
			Help: "Rows purged by scheduled cleanup tasks, labeled by target table.",
		},
		[]string{"table"},
	)
)

// RecordStripeBreakerState updates the global breaker state gauge. Called
// from the breaker's OnStateChange hook. Values mirror gobreaker's semantics:
// 0=closed (normal), 1=half_open (probing), 2=open (rejecting).
func RecordStripeBreakerState(state string) {
	var v float64
	switch state {
	case "half_open":
		v = 1
	case "open":
		v = 2
	}
	stripeBreakerState.Set(v)
}

func init() {
	c := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "velox_audit_write_errors_total",
		Help: "Total failed audit log writes, labeled by tenant.",
	}, []string{"tenant_id"})
	if err := prometheus.DefaultRegisterer.Register(c); err != nil {
		// Already registered by another package — reuse the existing collector.
		if are, ok := err.(prometheus.AlreadyRegisteredError); ok {
			auditWriteErrors = are.ExistingCollector.(*prometheus.CounterVec)
		} else {
			panic(err)
		}
	} else {
		auditWriteErrors = c
	}
}

// Metrics returns middleware that records HTTP request metrics.
func Metrics() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.URL.Path == "/metrics" || r.URL.Path == "/health" {
				next.ServeHTTP(w, r)
				return
			}

			httpRequestsInFlight.Inc()
			defer httpRequestsInFlight.Dec()

			start := time.Now()
			ww := chimw.NewWrapResponseWriter(w, r.ProtoMajor)
			next.ServeHTTP(ww, r)

			status := strconv.Itoa(ww.Status())
			path := sanitizePath(r.URL.Path)
			duration := time.Since(start).Seconds()

			httpRequestsTotal.WithLabelValues(r.Method, path, status).Inc()
			httpRequestDuration.WithLabelValues(r.Method, path, status).Observe(duration)
		})
	}
}

// MetricsHandler returns the Prometheus metrics HTTP handler.
func MetricsHandler() http.Handler {
	return promhttp.Handler()
}

// RecordBillingCycle records billing cycle metrics.
func RecordBillingCycle(generated int) {
	billingCyclesTotal.Inc()
	invoicesGenerated.Add(float64(generated))
}

// RecordUsageIngested records usage event ingestion.
func RecordUsageIngested(count int) {
	usageEventsIngested.Add(float64(count))
}

// RecordBillingCycleDuration records how long a billing cycle took.
func RecordBillingCycleDuration(seconds float64) {
	billingCycleDuration.Observe(seconds)
}

// RecordBillingCycleError increments the billing cycle error counter.
func RecordBillingCycleError() {
	billingCycleErrors.Inc()
}

// RecordPaymentCharge records a payment charge result ("succeeded" or "failed").
func RecordPaymentCharge(result string) {
	paymentCharges.WithLabelValues(result).Inc()
}

// RecordWebhookDelivery records a webhook delivery status ("succeeded", "failed", or "pending").
func RecordWebhookDelivery(status string) {
	webhookDeliveries.WithLabelValues(status).Inc()
}

// RecordDunningRun increments the dunning runs processed counter.
func RecordDunningRun() {
	dunningRunsProcessed.Inc()
}

// RecordCreditOperation records a credit operation by type ("grant", "usage", "expiry", "adjustment").
func RecordCreditOperation(opType string) {
	creditOperations.WithLabelValues(opType).Inc()
}

// RecordAutoChargeRetry records an auto-charge retry result ("succeeded" or "failed").
func RecordAutoChargeRetry(result string) {
	autoChargeRetries.WithLabelValues(result).Inc()
}

// RecordScheduledCleanup records rows purged by a scheduled cleanup task.
// Label values match the target table (e.g. "idempotency_keys",
// "payment_tokens") so operators can alert per-table on sudden surges.
func RecordScheduledCleanup(table string, rows int) {
	if rows <= 0 {
		return
	}
	scheduledCleanupRows.WithLabelValues(table).Add(float64(rows))
}

// RecordAuditWriteError increments the per-tenant audit write error counter.
// SOC-2 operators alert on sum(audit_write_errors_total) and drill into the
// tenant_id label to find which tenants are affected.
func RecordAuditWriteError(tenantID string) {
	auditWriteErrors.WithLabelValues(tenantID).Inc()
}

// sanitizePath normalizes paths to prevent high-cardinality metric labels.
// Replaces dynamic segments (IDs) with placeholders.
func sanitizePath(path string) string {
	// Common patterns: /v1/customers/vlx_cus_abc123 → /v1/customers/:id
	parts := splitPath(path)
	for i, part := range parts {
		if isID(part) {
			parts[i] = ":id"
		}
	}
	return joinPath(parts)
}

func splitPath(path string) []string {
	var parts []string
	current := ""
	for _, c := range path {
		if c == '/' {
			if current != "" {
				parts = append(parts, current)
				current = ""
			}
		} else {
			current += string(c)
		}
	}
	if current != "" {
		parts = append(parts, current)
	}
	return parts
}

func joinPath(parts []string) string {
	result := ""
	for _, p := range parts {
		result += "/" + p
	}
	if result == "" {
		return "/"
	}
	return result
}

func isID(s string) bool {
	// Velox IDs start with vlx_ prefix
	if len(s) > 4 && s[:4] == "vlx_" {
		return true
	}
	// UUIDs and other long hex strings
	if len(s) > 20 {
		return true
	}
	return false
}
