package middleware

import (
	"net/http"
	"strconv"
	"time"

	chimw "github.com/go-chi/chi/v5/middleware"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	httpRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_http_requests_total",
			Help: "Total HTTP requests by method, path pattern, and status code.",
		},
		[]string{"method", "path", "status"},
	)

	httpRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "velox_http_request_duration_seconds",
			Help:    "HTTP request latency in seconds.",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
		},
		[]string{"method", "path", "status"},
	)

	httpRequestsInFlight = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "velox_http_requests_in_flight",
			Help: "Current number of HTTP requests being processed.",
		},
	)

	billingCyclesTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_billing_cycles_total",
			Help: "Total billing cycles executed.",
		},
	)

	// idempotencyCacheErrors counts idempotency-layer DB failures by stage.
	// Non-zero means the idempotency guarantee lapsed: a "reserve" failure
	// fell open (the handler ran without a claim, so a concurrent/retried
	// request could re-execute the side effect), and a "finalize" failure
	// means the response wasn't cached (a retry under the same key re-runs the
	// handler). Operators should alert on any sustained rate here.
	idempotencyCacheErrors = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_idempotency_cache_errors_total",
			Help: "Idempotency cache DB errors by stage (reserve|finalize).",
		},
		[]string{"stage"},
	)

	invoicesGenerated = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_invoices_generated_total",
			Help: "Total invoices generated by the billing engine.",
		},
	)

	usageEventsIngested = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_usage_events_ingested_total",
			Help: "Total usage events ingested.",
		},
	)

	billingCycleDuration = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "velox_billing_cycle_duration_seconds",
			Help:    "Duration of billing cycle runs in seconds.",
			Buckets: []float64{0.1, 0.5, 1, 2.5, 5, 10, 30, 60, 120, 300},
		},
	)

	billingCycleErrors = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_billing_cycle_errors_total",
			Help: "Total billing cycle errors.",
		},
	)

	paymentCharges = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_payment_charges_total",
			Help: "Total payment charges by result.",
		},
		[]string{"result"},
	)

	webhookDeliveries = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_webhook_deliveries_total",
			Help: "Total outbound webhook deliveries by status.",
		},
		[]string{"status"},
	)

	dunningRunsProcessed = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_dunning_runs_processed_total",
			Help: "Total dunning runs processed by outcome.",
		},
		[]string{"outcome"},
	)

	creditOperations = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_credit_operations_total",
			Help: "Total credit operations by type.",
		},
		[]string{"type"},
	)

	autoChargeRetries = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_auto_charge_retries_total",
			Help: "Total auto-charge retries by result.",
		},
		[]string{"result"},
	)

	reconcilerSweeps = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_reconciler_sweeps_total",
			Help: "Recovery reconciler sweeps by reconciler, mode, and outcome (run|advanced|error). 'run' increments every tick (liveness); 'advanced'/'error' carry the per-tick counts.",
		},
		[]string{"reconciler", "mode", "outcome"},
	)

	stripeBreakerState = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "velox_stripe_breaker_state",
			Help: "Global circuit breaker state for Stripe calls. 0=closed, 1=half_open, 2=open.",
		},
	)

	scheduledCleanupRows = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_scheduled_cleanup_rows_total",
			Help: "Rows purged by scheduled cleanup tasks, labeled by target table.",
		},
		[]string{"table"},
	)
)

// RecordStripeBreakerState updates the global breaker state gauge. Called
// from the breaker's OnStateChange hook. Values mirror gobreaker's semantics:
// 0=closed (normal), 1=half_open (probing), 2=open (rejecting).
func RecordStripeBreakerState(state string) {
	var v float64
	switch state {
	case "half_open":
		v = 1
	case "open":
		v = 2
	}
	stripeBreakerState.Set(v)
}

// Metrics returns middleware that records HTTP request metrics.
func Metrics() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.URL.Path == "/metrics" || r.URL.Path == "/health" {
				next.ServeHTTP(w, r)
				return
			}

			httpRequestsInFlight.Inc()
			defer httpRequestsInFlight.Dec()

			start := time.Now()
			ww := chimw.NewWrapResponseWriter(w, r.ProtoMajor)
			next.ServeHTTP(ww, r)

			status := strconv.Itoa(ww.Status())
			path := sanitizePath(r.URL.Path)
			duration := time.Since(start).Seconds()

			httpRequestsTotal.WithLabelValues(r.Method, path, status).Inc()
			httpRequestDuration.WithLabelValues(r.Method, path, status).Observe(duration)
		})
	}
}

// MetricsHandler returns the Prometheus metrics HTTP handler.
func MetricsHandler() http.Handler {
	return promhttp.Handler()
}

// RecordBillingCycle records billing cycle metrics.
func RecordBillingCycle(generated int) {
	billingCyclesTotal.Inc()
	invoicesGenerated.Add(float64(generated))
}

// RecordUsageIngested records usage event ingestion.
func RecordUsageIngested(count int) {
	usageEventsIngested.Add(float64(count))
}

// RecordBillingCycleDuration records how long a billing cycle took.
func RecordBillingCycleDuration(seconds float64) {
	billingCycleDuration.Observe(seconds)
}

// RecordBillingCycleError increments the billing cycle error counter.
func RecordBillingCycleError() {
	billingCycleErrors.Inc()
}

// RecordPaymentCharge records a payment charge result ("succeeded" or "failed").
func RecordPaymentCharge(result string) {
	paymentCharges.WithLabelValues(result).Inc()
}

// RecordWebhookDelivery records a webhook delivery status ("succeeded", "failed", or "pending").
func RecordWebhookDelivery(status string) {
	webhookDeliveries.WithLabelValues(status).Inc()
}

// RecordDunningRun records a processed dunning run outcome ("succeeded" or
// "failed"). The outcome split backs the runbook's dunning-machinery alert
// on {outcome="failed"} — without it, failed runs had zero metric visibility.
func RecordDunningRun(outcome string) {
	dunningRunsProcessed.WithLabelValues(outcome).Inc()
}

// RecordCreditOperation records a credit operation by type ("grant", "usage", "expiry", "adjustment").
func RecordCreditOperation(opType string) {
	creditOperations.WithLabelValues(opType).Inc()
}

// RecordAutoChargeRetry records an auto-charge retry result ("succeeded" or "failed").
func RecordAutoChargeRetry(result string) {
	autoChargeRetries.WithLabelValues(result).Inc()
}

// RecordReconcilerSweep records one recovery-reconciler sweep: a 'run' tick
// (always, so operators can alert on a reconciler that stops running), plus the
// items advanced and per-row errors this tick. `mode` is "live"/"test".
// Powers per-reconciler dashboards/alerts (e.g. a stuck tax-reversal backlog) —
// previously only auto-charge was metered.
func RecordReconcilerSweep(reconciler, mode string, advanced, errs int) {
	reconcilerSweeps.WithLabelValues(reconciler, mode, "run").Inc()
	if advanced > 0 {
		reconcilerSweeps.WithLabelValues(reconciler, mode, "advanced").Add(float64(advanced))
	}
	if errs > 0 {
		reconcilerSweeps.WithLabelValues(reconciler, mode, "error").Add(float64(errs))
	}
}

// RecordScheduledCleanup records rows purged by a scheduled cleanup task.
// Label values match the target table (e.g. "idempotency_keys",
// "payment_tokens") so operators can alert per-table on sudden surges.
func RecordScheduledCleanup(table string, rows int) {
	if rows <= 0 {
		return
	}
	scheduledCleanupRows.WithLabelValues(table).Add(float64(rows))
}

// sanitizePath normalizes paths to prevent high-cardinality metric labels.
// Replaces dynamic segments (IDs) with placeholders.
func sanitizePath(path string) string {
	// Common patterns: /v1/customers/vlx_cus_abc123 → /v1/customers/:id
	parts := splitPath(path)
	for i, part := range parts {
		if isID(part) {
			parts[i] = ":id"
		}
	}
	return joinPath(parts)
}

func splitPath(path string) []string {
	var parts []string
	current := ""
	for _, c := range path {
		if c == '/' {
			if current != "" {
				parts = append(parts, current)
				current = ""
			}
		} else {
			current += string(c)
		}
	}
	if current != "" {
		parts = append(parts, current)
	}
	return parts
}

func joinPath(parts []string) string {
	result := ""
	for _, p := range parts {
		result += "/" + p
	}
	if result == "" {
		return "/"
	}
	return result
}

func isID(s string) bool {
	// Velox IDs start with vlx_ prefix
	if len(s) > 4 && s[:4] == "vlx_" {
		return true
	}
	// UUIDs and other long hex strings
	if len(s) > 20 {
		return true
	}
	return false
}

// schedulerLastRunTimestamp backs the runbook's "scheduler is alive" alert:
// `time() - velox_scheduler_last_run_timestamp_seconds > 2 * interval`.
// Pre-2026-07-06 the runbook told operators to alert on scheduler last-run
// age with NO exported metric (only /health/ready encoded it).
var schedulerLastRunTimestamp = promauto.NewGauge(
	prometheus.GaugeOpts{
		Name: "velox_scheduler_last_run_timestamp_seconds",
		Help: "Unix timestamp of the billing scheduler's last completed tick. Alert when time() - this > 2x the scheduler interval.",
	},
)

// RecordSchedulerTick stamps the scheduler-liveness gauge; called by the
// same hook that feeds /health/ready.
func RecordSchedulerTick() {
	schedulerLastRunTimestamp.SetToCurrentTime()
}

// RegisterQueueDepthGauges exports the queue-depth gauges the shipped
// Grafana dashboard and runbook alert on. Pre-2026-07-06 the dashboard
// queried velox_email_outbox_pending / velox_webhook_outbox_pending /
// velox_dunning_active_runs masked by `OR vector(0)` — gauges the binary
// never exported, so the panels flatlined at 0 through a real backlog.
//
// Gauges resolve at SCRAPE time via one COUNT each (cheap: partial/status
// indexes; 3s cap). A query failure reports -1 — visibly wrong rather than
// a healthy-looking 0.
func RegisterQueueDepthGauges(count func(query string) (float64, error)) {
	gauge := func(name, help, query string) {
		promauto.NewGaugeFunc(prometheus.GaugeOpts{Name: name, Help: help}, func() float64 {
			n, err := count(query)
			if err != nil {
				return -1
			}
			return n
		})
	}
	gauge("velox_email_outbox_pending",
		"Emails waiting for the outbox dispatcher (status='pending'). -1 = metric query failed.",
		`SELECT COUNT(*) FROM email_outbox WHERE status = 'pending'`)
	gauge("velox_webhook_outbox_pending",
		"Outbound webhook events waiting for the outbox dispatcher (status='pending'). -1 = metric query failed.",
		`SELECT COUNT(*) FROM webhook_outbox WHERE status = 'pending'`)
	gauge("velox_dunning_active_runs",
		"Dunning runs currently active. -1 = metric query failed.",
		`SELECT COUNT(*) FROM invoice_dunning_runs WHERE state = 'active'`)
	gauge("velox_creditnote_pending_issue_drafts",
		"Clawback credit-note drafts awaiting issue (issue_pending, status='draft') — includes drafts legitimately deferred behind an in-flight source payment (ADR-059); alert on sustained growth/age, not presence. -1 = metric query failed.",
		`SELECT COUNT(*) FROM credit_notes WHERE issue_pending AND status = 'draft'`)
}
