package middleware

import (
	"net/http"
	"strconv"
	"time"

	chimw "github.com/go-chi/chi/v5/middleware"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	httpRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_http_requests_total",
			Help: "Total HTTP requests by method, path pattern, and status code.",
		},
		[]string{"method", "path", "status"},
	)

	httpRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "velox_http_request_duration_seconds",
			Help:    "HTTP request latency in seconds.",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
		},
		[]string{"method", "path", "status"},
	)

	httpRequestsInFlight = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "velox_http_requests_in_flight",
			Help: "Current number of HTTP requests being processed.",
		},
	)

	billingCyclesTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_billing_cycles_total",
			Help: "Total billing cycles executed.",
		},
	)

	invoicesGenerated = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_invoices_generated_total",
			Help: "Total invoices generated by the billing engine.",
		},
	)

	usageEventsIngested = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_usage_events_ingested_total",
			Help: "Total usage events ingested.",
		},
	)
)

// Metrics returns middleware that records HTTP request metrics.
func Metrics() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.URL.Path == "/metrics" || r.URL.Path == "/health" {
				next.ServeHTTP(w, r)
				return
			}

			httpRequestsInFlight.Inc()
			defer httpRequestsInFlight.Dec()

			start := time.Now()
			ww := chimw.NewWrapResponseWriter(w, r.ProtoMajor)
			next.ServeHTTP(ww, r)

			status := strconv.Itoa(ww.Status())
			path := sanitizePath(r.URL.Path)
			duration := time.Since(start).Seconds()

			httpRequestsTotal.WithLabelValues(r.Method, path, status).Inc()
			httpRequestDuration.WithLabelValues(r.Method, path, status).Observe(duration)
		})
	}
}

// MetricsHandler returns the Prometheus metrics HTTP handler.
func MetricsHandler() http.Handler {
	return promhttp.Handler()
}

// RecordBillingCycle records billing cycle metrics.
func RecordBillingCycle(generated int) {
	billingCyclesTotal.Inc()
	invoicesGenerated.Add(float64(generated))
}

// RecordUsageIngested records usage event ingestion.
func RecordUsageIngested(count int) {
	usageEventsIngested.Add(float64(count))
}

// sanitizePath normalizes paths to prevent high-cardinality metric labels.
// Replaces dynamic segments (IDs) with placeholders.
func sanitizePath(path string) string {
	// Common patterns: /v1/customers/vlx_cus_abc123 → /v1/customers/:id
	parts := splitPath(path)
	for i, part := range parts {
		if isID(part) {
			parts[i] = ":id"
		}
	}
	return joinPath(parts)
}

func splitPath(path string) []string {
	var parts []string
	current := ""
	for _, c := range path {
		if c == '/' {
			if current != "" {
				parts = append(parts, current)
				current = ""
			}
		} else {
			current += string(c)
		}
	}
	if current != "" {
		parts = append(parts, current)
	}
	return parts
}

func joinPath(parts []string) string {
	result := ""
	for _, p := range parts {
		result += "/" + p
	}
	if result == "" {
		return "/"
	}
	return result
}

func isID(s string) bool {
	// Velox IDs start with vlx_ prefix
	if len(s) > 4 && s[:4] == "vlx_" {
		return true
	}
	// UUIDs and other long hex strings
	if len(s) > 20 {
		return true
	}
	return false
}
