package testclock

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/sagarsuperuser/velox/internal/api/respond"
	"github.com/sagarsuperuser/velox/internal/auth"
	"github.com/sagarsuperuser/velox/internal/domain"
	"github.com/sagarsuperuser/velox/internal/platform/clock"
)

// AuditWriter is the narrow audit surface testclock uses.
type AuditWriter interface {
	Log(ctx context.Context, tenantID, action, resourceType, resourceID, resourceLabel string, metadata map[string]any) error
}

// Handler exposes /v1/test-clocks. Auth middleware upstream enforces that the
// caller holds a test-mode key (livemode=false); the service itself adds a
// second guard so a misconfigured auth chain can't slip live writes through.
type Handler struct {
	svc         *Service
	auditLogger AuditWriter
}

func NewHandler(svc *Service) *Handler {
	return &Handler{svc: svc}
}

// SetAuditLogger wires audit on test-clock lifecycle. Critical for
// forensics: "was this invoice generated by a real cycle or by an
// operator advancing a sim clock?" is answered by cross-referencing
// the clock advance audit row with the invoice's issued_at.
func (h *Handler) SetAuditLogger(a AuditWriter) {
	h.auditLogger = a
}

func (h *Handler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Use(h.requireTestMode)
	r.Post("/", h.create)
	r.Get("/", h.list)
	r.Get("/{id}", h.get)
	r.Get("/{id}/subscriptions", h.listSubscriptions)
	r.Get("/{id}/customers", h.listAttachedCustomers)
	r.Post("/{id}/advance", h.advance)
	r.Post("/{id}/retry-advance", h.retryAdvance)
	r.Delete("/{id}", h.delete)
	return r
}

// requireTestMode short-circuits requests from live-mode keys with 403. The
// underlying table enforces livemode=false via CHECK, so a live call would
// eventually fail anyway — this makes the failure immediate and explains why.
func (h *Handler) requireTestMode(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if auth.Livemode(r.Context()) {
			respond.Forbidden(w, r, "test clocks are only available in test mode — use a test-mode API key (vlx_secret_test_...)")
			return
		}
		next.ServeHTTP(w, r)
	})
}

func (h *Handler) create(w http.ResponseWriter, r *http.Request) {
	tenantID := auth.TenantID(r.Context())

	var input CreateInput
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		respond.BadRequest(w, r, "invalid JSON body")
		return
	}

	clk, err := h.svc.Create(r.Context(), tenantID, input)
	if err != nil {
		respond.FromError(w, r, err, "test_clock")
		return
	}
	if h.auditLogger != nil {
		_ = h.auditLogger.Log(h.auditCtx(r.Context(), clk), tenantID, domain.AuditActionCreate, "test_clock", clk.ID, clk.Name, map[string]any{
			"frozen_time": clk.FrozenTime,
		})
	}
	respond.JSON(w, r, http.StatusCreated, clk)
}

// auditCtx puts a test_clock row ON ITS OWN CLOCK'S sim axis: the clock is
// both the resource and the pin, so sim_effective_at is the frozen instant the
// clock stood at when the operator acted.
//
// This is what makes the clock filter self-contained after ADR-086 teardown.
// Teardown hard-deletes every simulated business row, so a clock-scoped
// forensic view is reconstructed entirely from audit_log — and without these
// rows it would have the effects (invoices finalized, subs canceled) but not
// the CAUSE: no "created", no "advanced to 2027-03-01", and no "deleted", which
// is the row that explains why every other trace of the simulation is gone.
func (h *Handler) auditCtx(ctx context.Context, clk domain.TestClock) context.Context {
	return clock.WithSim(ctx, clock.Sim{At: clk.FrozenTime, TestClockID: clk.ID})
}

func (h *Handler) list(w http.ResponseWriter, r *http.Request) {
	tenantID := auth.TenantID(r.Context())

	clocks, err := h.svc.List(r.Context(), tenantID)
	if err != nil {
		respond.InternalError(w, r)
		slog.ErrorContext(r.Context(), "list test clocks", "error", err)
		return
	}
	if clocks == nil {
		clocks = []domain.TestClock{}
	}
	respond.JSON(w, r, http.StatusOK, map[string]any{"data": clocks})
}

func (h *Handler) get(w http.ResponseWriter, r *http.Request) {
	tenantID := auth.TenantID(r.Context())
	id := chi.URLParam(r, "id")

	clk, err := h.svc.Get(r.Context(), tenantID, id)
	if err != nil {
		respond.FromError(w, r, err, "test_clock")
		return
	}
	respond.JSON(w, r, http.StatusOK, clk)
}

// listSubscriptions returns every subscription pinned to the clock,
// including their customer for one-shot rendering on the clock detail
// page. The dashboard uses the embedded customer_id to compose the
// "customers in this simulation" view without a second round-trip.
func (h *Handler) listSubscriptions(w http.ResponseWriter, r *http.Request) {
	tenantID := auth.TenantID(r.Context())
	id := chi.URLParam(r, "id")

	subs, err := h.svc.ListSubscriptions(r.Context(), tenantID, id)
	if err != nil {
		respond.FromError(w, r, err, "test_clock")
		return
	}
	if subs == nil {
		subs = []domain.Subscription{}
	}
	respond.JSON(w, r, http.StatusOK, map[string]any{"data": subs})
}

// listAttachedCustomers returns customers attached to this clock —
// Stripe-parity surface (ADR-027 Tier 3). The clock detail page uses
// this to render the "Attached customers" section, mirroring Stripe
// Test Clock detail's UI.
func (h *Handler) listAttachedCustomers(w http.ResponseWriter, r *http.Request) {
	tenantID := auth.TenantID(r.Context())
	id := chi.URLParam(r, "id")

	customers, err := h.svc.ListAttachedCustomers(r.Context(), tenantID, id)
	if err != nil {
		respond.FromError(w, r, err, "test_clock")
		return
	}
	if customers == nil {
		customers = []domain.Customer{}
	}
	respond.JSON(w, r, http.StatusOK, map[string]any{"data": customers})
}

func (h *Handler) advance(w http.ResponseWriter, r *http.Request) {
	tenantID := auth.TenantID(r.Context())
	id := chi.URLParam(r, "id")

	var input AdvanceInput
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		respond.BadRequest(w, r, "invalid JSON body")
		return
	}

	// Read the clock BEFORE advancing so the audit row can record the WINDOW the
	// advance swept, not just where it landed. Without the "from" instant, an
	// advance row says "the clock is now at 2027-06-01" and nothing else — so the
	// events it caused (every invoice, cancel and dunning step settled in that
	// sweep) cannot be bounded to it. After ADR-086 teardown these rows are the
	// ONLY surviving record of the simulation, and "which advance produced this?"
	// is precisely the question they exist to answer.
	//
	// Best-effort: a read failure must not block the operator's advance. The row
	// then carries the destination alone, exactly as it always did.
	var advancedFrom *time.Time
	if before, gerr := h.svc.Get(r.Context(), tenantID, id); gerr == nil {
		from := before.FrozenTime
		advancedFrom = &from
	}

	clk, err := h.svc.Advance(r.Context(), tenantID, id, input)
	if err != nil {
		respond.FromError(w, r, err, "test_clock")
		return
	}
	if h.auditLogger != nil {
		meta := map[string]any{
			"action":      "advanced",
			"frozen_time": clk.FrozenTime,
		}
		if advancedFrom != nil {
			meta["advanced_from"] = *advancedFrom
		}
		_ = h.auditLogger.Log(h.auditCtx(r.Context(), clk), tenantID, domain.AuditActionUpdate, "test_clock", clk.ID, clk.Name, meta)
	}
	respond.JSON(w, r, http.StatusOK, clk)
}

// retryAdvance resumes a clock parked at status='internal_failure'
// after a prior catchup error. The catchup loop is idempotent on
// subs whose next_billing_at <= frozen_time, so resuming from
// where the previous attempt stopped is safe by construction.
// 200 with the clock now in 'advancing' on success; 409 when the
// clock isn't in internal_failure (refuses to retry from ready
// or advancing). ADR-018.
func (h *Handler) retryAdvance(w http.ResponseWriter, r *http.Request) {
	tenantID := auth.TenantID(r.Context())
	id := chi.URLParam(r, "id")

	clk, err := h.svc.RetryAdvance(r.Context(), tenantID, id)
	if err != nil {
		respond.FromError(w, r, err, "test_clock")
		return
	}
	if h.auditLogger != nil {
		_ = h.auditLogger.Log(h.auditCtx(r.Context(), clk), tenantID, domain.AuditActionUpdate, "test_clock", clk.ID, clk.Name, map[string]any{
			"action":      "retry_advance",
			"frozen_time": clk.FrozenTime,
		})
	}
	respond.JSON(w, r, http.StatusOK, clk)
}

func (h *Handler) delete(w http.ResponseWriter, r *http.Request) {
	tenantID := auth.TenantID(r.Context())
	id := chi.URLParam(r, "id")

	// Read the clock BEFORE the teardown: after Delete it does not exist, and
	// this row is the one that has to survive it. ADR-086 teardown hard-deletes
	// the clock's entire simulated customer graph, so "deleted TC-x, frozen at
	// 2027-03-01, N customers" is the last thing the audit log can say about the
	// simulation — and the reason a clock-scoped query returns nothing else.
	// A failed read costs the sim axis on this row, never the deletion.
	auditCtx := r.Context()
	label := ""
	if clk, err := h.svc.Get(r.Context(), tenantID, id); err == nil {
		auditCtx = h.auditCtx(auditCtx, clk)
		label = clk.Name
	}

	if err := h.svc.Delete(r.Context(), tenantID, id); err != nil {
		respond.FromError(w, r, err, "test_clock")
		return
	}
	if h.auditLogger != nil {
		_ = h.auditLogger.Log(auditCtx, tenantID, domain.AuditActionDelete, "test_clock", id, label, map[string]any{
			"action": "teardown",
		})
	}
	respond.JSON(w, r, http.StatusOK, map[string]string{"status": "deleted"})
}
