package domain

import "time"

type CreditEntryType string

const (
	CreditGrant      CreditEntryType = "grant"
	CreditUsage      CreditEntryType = "usage"
	CreditExpiry     CreditEntryType = "expiry"
	CreditAdjustment CreditEntryType = "adjustment"
)

type CreditLedgerEntry struct {
	ID           string          `json:"id"`
	TenantID     string          `json:"tenant_id,omitempty"`
	CustomerID   string          `json:"customer_id"`
	EntryType    CreditEntryType `json:"entry_type"`
	AmountCents  int64           `json:"amount_cents"`
	BalanceAfter int64           `json:"balance_after"`
	Description  string          `json:"description"`
	InvoiceID    string          `json:"invoice_id,omitempty"`
	ExpiresAt    *time.Time      `json:"expires_at,omitempty"`
	Metadata     map[string]any  `json:"metadata,omitempty"`
	CreatedAt    time.Time       `json:"created_at"`
	// ConsumedCents tracks how much of a grant's amount has been
	// drained by FIFO-attributed usage entries (Orb's credit-block
	// model). Meaningful only for entry_type='grant'; 0 for usage /
	// expiry / adjustment. Grant remaining = amount_cents -
	// consumed_cents. Expiry deducts only the remaining (un-drained)
	// portion — never the original amount — so an already-consumed
	// grant expiring is a no-op rather than a balance underflow.
	ConsumedCents int64 `json:"consumed_cents,omitempty"`

	// SourceSubscriptionID + SourceSubscriptionItemID + SourcePlanChangedAt +
	// SourceChangeType, when all set, identify this entry as a proration
	// credit generated by an item mutation (downgrade plan change, qty
	// reduction, item remove). Combined with TenantID they form the natural
	// key used to dedup retries of proration grant — see migrations 0026 +
	// 0027 (item id + change_type disambiguate simultaneous mutations of
	// different kinds that share a wall-clock timestamp).
	SourceSubscriptionID     string         `json:"source_subscription_id,omitempty"`
	SourceSubscriptionItemID string         `json:"source_subscription_item_id,omitempty"`
	SourcePlanChangedAt      *time.Time     `json:"source_plan_changed_at,omitempty"`
	SourceChangeType         ItemChangeType `json:"source_change_type,omitempty"`

	// SourceCreditNoteID dedups grants created by credit-note Issue().
	// Set on every grant the CN refund-routing path appends; the
	// partial unique index idx_credit_ledger_credit_note_dedup
	// (migration 0093) enforces one grant per (tenant, CN). A retry
	// after partial-failure of CN Issue() hits the index, store
	// returns ErrAlreadyExists, service fetches the existing grant.
	SourceCreditNoteID string `json:"source_credit_note_id,omitempty"`
}

type CreditBalance struct {
	CustomerID   string `json:"customer_id"`
	BalanceCents int64  `json:"balance_cents"`
	TotalGranted int64  `json:"total_granted"`
	TotalUsed    int64  `json:"total_used"`
	TotalExpired int64  `json:"total_expired"`
}
