package domain

import "time"

type CreditEntryType string

const (
	CreditGrant      CreditEntryType = "grant"
	CreditUsage      CreditEntryType = "usage"
	CreditExpiry     CreditEntryType = "expiry"
	CreditAdjustment CreditEntryType = "adjustment"
)

type CreditLedgerEntry struct {
	ID           string          `json:"id"`
	TenantID     string          `json:"tenant_id,omitempty"`
	CustomerID   string          `json:"customer_id"`
	EntryType    CreditEntryType `json:"entry_type"`
	AmountCents  int64           `json:"amount_cents"`
	BalanceAfter int64           `json:"balance_after"`
	Description  string          `json:"description"`
	InvoiceID    string          `json:"invoice_id,omitempty"`
	ExpiresAt    *time.Time      `json:"expires_at,omitempty"`
	Metadata     map[string]any  `json:"metadata,omitempty"`
	CreatedAt    time.Time       `json:"created_at"`

	// SourceSubscriptionID + SourceSubscriptionItemID + SourcePlanChangedAt,
	// when all set, identify this entry as a proration credit generated by a
	// downgrade plan change on a specific item. Combined with TenantID they
	// form the natural key used to dedup retries of proration grant — see
	// migration 0026 (item id disambiguates two items whose changes landed at
	// the same wall-clock timestamp).
	SourceSubscriptionID     string     `json:"source_subscription_id,omitempty"`
	SourceSubscriptionItemID string     `json:"source_subscription_item_id,omitempty"`
	SourcePlanChangedAt      *time.Time `json:"source_plan_changed_at,omitempty"`
}

type CreditBalance struct {
	CustomerID   string `json:"customer_id"`
	BalanceCents int64  `json:"balance_cents"`
	TotalGranted int64  `json:"total_granted"`
	TotalUsed    int64  `json:"total_used"`
	TotalExpired int64  `json:"total_expired"`
}
