-- Optimistic concurrency lock for coupon updates.
--
-- The PATCH /coupons/:id endpoint accepts an If-Match header carrying the
-- ETag the client last saw. The UPDATE SQL gates on this column so two
-- concurrent operators editing the same coupon can't silently overwrite
-- each other — the loser gets a 412 Precondition Failed and is expected
-- to refetch and retry.
--
-- Existing rows default to 1 so the first post-migration write advances
-- to 2 and the ETag becomes meaningful immediately. NOT NULL so scan
-- paths can read into an int without a COALESCE.
ALTER TABLE coupons ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
