-- Allow one-off invoices: subscription_id becomes nullable.
--
-- Background: invoices.subscription_id was NOT NULL because every cycle
-- invoice originates from a subscription. With the customer-page invoice
-- composer (Week 7) we ship one-off invoices that have no parent
-- subscription. Making the column nullable is the cleanest way to model
-- this without a separate "manual_invoices" table or a synthetic-sub
-- shim. List/get/finalize/void/send all already tolerate empty/null
-- subscription_id at the read path.
--
-- The existing partial unique index on
-- (tenant_id, subscription_id, billing_period_start, billing_period_end)
-- WHERE status != 'voided' enforces "one cycle invoice per period". With
-- a nullable column Postgres treats NULL as distinct from NULL, so two
-- one-off invoices with no subscription can coexist for the same
-- billing_period — exactly what we want. The index keeps its cycle-
-- idempotency guarantee for subscription-bound invoices unchanged.
ALTER TABLE invoices ALTER COLUMN subscription_id DROP NOT NULL;
