-- Persist Stripe's per-line `taxability_reason` (closes #4). Two invoices
-- both showing tax_amount=0 need different PDF legends — reverse_charge
-- (EU B2B "VAT to be accounted for by the recipient") vs not_collecting
-- (merchant has no registration in this jurisdiction; no legend required)
-- vs customer_exempt (customer's exemption certificate) — and that
-- distinction is impossible without storing the per-line reason.
--
-- Treated as an opaque string (Stripe may add new reasons over time);
-- known values surface as badges in the dashboard and exemption legends
-- in the PDF, unknown values round-trip without breaking the UI.
--
-- Display/legend column only — never queried, no index needed.
ALTER TABLE invoice_line_items ADD COLUMN tax_reason TEXT NOT NULL DEFAULT '';
