-- Default dunning final_action: 'manual_review' → 'pause'.
--
-- Rationale: with manual_review (the prior default), a subscription
-- whose dunning has exhausted stays `active`, the engine keeps
-- generating finalized invoices each cycle, each one fires a fresh
-- dunning run, and the customer keeps receiving emails per cycle —
-- the invoice-stacking failure mode that the audit flagged.
--
-- Flipping the default to `pause` makes the right thing happen by
-- default: `pause_collection.behavior = keep_as_draft` is set,
-- subsequent cycles generate as DRAFT (not finalized), and no
-- per-cycle dunning emails fire. Operators who want a different
-- terminal action explicitly set `manual_review` or
-- `write_off_later`; the schema-level CHECK still permits all three.
--
-- Forward-looking only — affects new dunning_policies rows. Existing
-- tenants who already have a policy keep their current value (pre-
-- launch backfill is a one-off SQL UPDATE; not codified here so the
-- migration stays idempotent across replays).

ALTER TABLE dunning_policies ALTER COLUMN final_action SET DEFAULT 'pause';
