-- Surface why a catchup failed, and let the operator retry without
-- destroying simulation state (ADR-018).
--
-- Pre-fix: when the async catchup worker errored, it called
-- MarkFailed which flipped the clock to status='internal_failure'
-- with no record of WHY. The operator-facing card said:
--
--     Catchup failed during last advance.
--     Some invoices may have been generated before the failure.
--     Inspect billing state, then delete this clock to start a
--     new simulation.
--
-- Two problems: (1) failure reason invisible — operator had to
-- grep server logs / audit_log to find the actual error; (2) only
-- recovery path was DELETE + rebuild — punishing for transient
-- failures (Stripe Tax 503, the now-fixed tenant-id-on-ctx bug,
-- intentionally-removed-creds debug runs). Stripe Test Clocks
-- offer a "Retry advance" button on the same wedged state and
-- their docs explicitly recommend retry over delete; the catchup
-- loop is idempotent (only processes subs whose next_billing_at
-- <= frozen_time), so resuming from where it stopped is safe.
--
-- This column stores the error message captured when MarkFailed
-- was last called. Truncated by application code to a sane
-- length (~500 chars) before write — full payload stays in the
-- structured slog line.

ALTER TABLE test_clocks ADD COLUMN last_failure_reason TEXT;
