-- Drop usage_events.subscription_id — never populated, never read.
--
-- The column was added with the original usage_events table on the
-- assumption that an event would carry a denormalized link to the
-- sub it was billed under. In practice:
--
--   - The HTTP ingest API (POST /v1/usage-events) never accepted it.
--   - The OpenAPI UsageEvent schema never advertised it.
--   - No internal caller (handler, bench tool, test fixtures) sets it.
--   - Billing finalize keys on (customer_id, meter_id, period) — the
--     sub is resolved from the period's owner, not from the event.
--   - DB audit at drop-time: 49,751 rows in usage_events, zero with
--     subscription_id populated.
--
-- Industry parallel: Stripe Meter Events do NOT carry a subscription
-- reference at all — the sub is figured out at invoice time. Lago,
-- Orb and Metronome follow the same late-binding shape. Velox's
-- previous design tried to keep an audit-only denorm hint; nothing
-- ever actually wired the audit path, so the field has been pure
-- structural dead weight.
--
-- Drop the FK first (added in 0015) so the column drop doesn't fail
-- on a constraint that references it.
ALTER TABLE usage_events DROP CONSTRAINT IF EXISTS usage_events_subscription_id_fkey;
ALTER TABLE usage_events DROP COLUMN IF EXISTS subscription_id;
