-- Drop test_clocks.deletes_after — never populated, sweeper had no
-- producer.
--
-- The column was added in migration 0020 (test_mode bootstrap) as a
-- Stripe-parity hook for the 30-day idle test-clock cleanup that
-- Stripe Test Clocks ship. ADR-016 (2026-05-04) wired the sweeper
-- side: a scheduler tick that soft-deletes any clock whose
-- deletes_after has elapsed and cascade-cancels its pinned subs.
--
-- The producer side never landed. Nothing in Velox writes
-- deletes_after — not the create endpoint, not the service, not the
-- SPA, not a background job. The column has been NULL on every row
-- in production since 0020, and the sweeper has matched zero rows
-- on every tick since ADR-016. The only thing that has ever set a
-- value is a manual psql command in MANUAL_TEST FLOW TC2 — testing
-- the sweeper machinery, not a feature an operator triggers.
--
-- Removing the column, the partial index, the sweeper interface,
-- the scheduler step, and the MANUAL_TEST flow that exists only
-- to exercise the dead code. If a customer later asks for
-- auto-cleanup, wiring it back is a half-day ADR — write a
-- creation-time TTL default, restore the sweeper, done. Today
-- it's pure structural debt.
--
-- The partial index is dropped first so the column drop doesn't
-- need CASCADE to clean up the index dependency.
DROP INDEX IF EXISTS idx_test_clocks_deletes;
ALTER TABLE test_clocks DROP COLUMN IF EXISTS deletes_after;
