-- Drop the customer_payment_setups summary table. Single source of
-- truth lives elsewhere now:
--   - customers.stripe_customer_id is the 1:1 Stripe Customer mapping
--     (migration 0096; backfilled from customer_payment_setups before
--     this migration runs).
--   - payment_methods is the canonical multi-PM store (migration 0022).
--   - billing.PaymentReadiness composes the "can we charge?" answer
--     from these two sources via paymentReadinessAdapter.
--   - compositePaymentSetupStore presents the legacy domain.CustomerPaymentSetup
--     wire shape (read + the narrow stripe_customer_id write path)
--     for code that hasn't been refactored to call the canonical
--     sources directly yet (payment/checkout.go's createSetupSession,
--     payment/stripe.go's checkout.session.completed webhook, the
--     dunning retrier, invoice handler). Those callers structurally
--     can't read or write the deprecated table because their
--     PaymentSetupStore-shaped dependency now resolves to the adapter,
--     not customer.PostgresStore.
--
-- After this migration the table no longer exists; any remaining
-- compile-time references to customer.PostgresStore.{Get,Upsert}PaymentSetup
-- would fail to run. Those methods are also being removed in the
-- same change set.

DROP TABLE IF EXISTS customer_payment_setups;
