-- Collapse the dual-email architecture to a single canonical
-- recipient: customers.email. Drop customer_billing_profiles.email.
--
-- Why: industry research (Stripe, Chargebee, Recurly, Lago, Orb) shows
-- no major platform uses Velox's prior shape — "billing_profile.email
-- overrides customers.email for sends". Stripe uses a single
-- customer.email; Recurly maintains separate fields but explicitly
-- only sends from the primary; Chargebee uses additional-contact rows
-- (Option 2 in our design audit). The two-column override was
-- architectural drift introduced before the bounce-tracking flow was
-- wired and broke the suppression key once recipients diverged.
--
-- Phase 1: single canonical email (Stripe shape). Phase 2 (when first
-- DP asks for multi-recipient): add customer_email_contacts table
-- as an additive layer with its own per-contact bounce tracking.
-- customers.email remains the primary recipient in both phases.
--
-- Safe to drop pre-launch: zero design partners, zero production
-- tenants. The column was rarely populated; existing test data is
-- disposable. Email values that DID exist are not migrated to
-- customers.email by this migration because there's no automated way
-- to choose which one wins for tenants that had both — operators set
-- the canonical via the customer-level edit flow.

ALTER TABLE customer_billing_profiles DROP COLUMN IF EXISTS email;
