-- Record whether a credit note was issued in simulated (test-clock) time.
--
-- Credit notes have two issuance paths with DIFFERENT time domains:
--   - operator HTTP issue → wall-clock (the handler doesn't bind the
--     customer's test clock), so issued_at is real time.
--   - engine clawback (subscription downgrade / cancel proration, ADR-048)
--     → simulated, because it runs under the clock-pinned sub's bound
--     effective-now, so issued_at is in the invoice's simulated time.
--
-- The invoice activity timeline routes wall-clock events to the "Real-time
-- activity" lane and simulated events to the "Activity" lane. Without a
-- per-CN flag the timeline assumed ALL credit notes were wall-clock and put
-- engine-issued ones in the real-time lane with a simulated timestamp — a
-- visible mismatch. This column lets the timeline lane each CN by its own
-- authoritative time domain instead of guessing from the invoice or the
-- reason string.
--
-- DEFAULT false: existing rows are assumed wall-clock; an engine-issued CN
-- predating this column keeps its old (mis-laned) display until corrected
-- directly. New rows are stamped by the issuer.
ALTER TABLE credit_notes ADD COLUMN is_simulated BOOLEAN NOT NULL DEFAULT false;
