-- The payment_intent_id for which this invoice's payment-FAILURE notification
-- set has already fired: the payment.failed outbound webhook, the customer
-- "payment failed" email, and auto-started dunning.
--
-- Why a dedicated marker and not payment_status:
--   1. Failure is NON-terminal. An invoice legitimately re-fails once per
--      dunning retry, each attempt a distinct PaymentIntent, so
--      payment_status='failed' alone can't tell "the same failure delivered
--      twice" (at-least-once webhook redelivery) apart from "a new retry that
--      also failed" (a genuinely new event that SHOULD notify again).
--   2. The synchronous charge path stamps payment_status='failed' WITHOUT
--      firing the notifications — it defers them to the
--      payment_intent.payment_failed webhook — so the status is already
--      'failed' before the notification path even runs. A status-keyed gate
--      would wrongly suppress that webhook's notifications.
--
-- This column is written ONLY by the notification path
-- (MarkPaymentFailedReportingTransition): SettleFailed fires the set exactly
-- once per (invoice, payment_intent_id) by checking whether this column
-- already equals the failing PI. NULL = no failure notification has fired yet.
ALTER TABLE invoices ADD COLUMN failure_notified_pi TEXT;
