-- A compact record of what the LAST advance produced, so the operator sees
-- "this advance generated 3 invoices, fired 1 dunning step, expired 2 credit
-- grants" without hunting across the Invoices / Audit / Dunning pages.
--
-- The billing catchup already computes these counts per phase (it just
-- discarded them); this column persists the accumulated summary so the
-- dashboard can render it after the clock polls back to status='ready'.
-- Stripe/Chargebee surface the same after-advance information; the clock
-- object itself carries no embedded summary there, but with a self-hosted
-- single-binary deployment persisting it on the clock row is the cheapest
-- correct shape (no separate endpoint, no advance-events table).
--
-- Nullable: a clock that has never been advanced (or whose advance ran with
-- no billing wired) has none. Overwritten on each advance.
ALTER TABLE test_clocks ADD COLUMN last_advance_summary JSONB;
