-- A self-clearing marker for the upstream tax-reversal recovery sweep.
--
-- Void / MarkUncollectible reverse the invoice's committed Stripe Tax
-- transaction (so the authority stops reporting it as collected). That call is
-- an external Stripe request and best-effort: a transient failure left the
-- invoice flipped locally but the tax STILL committed upstream → the tenant
-- over-remits, with no retry. The tax-COMMIT path already has a recovery
-- reconciler (#267 RetryPendingTaxCommit); the symmetric reversal path had none.
--
-- This column is the durable signal the new RetryPendingTaxReversal sweep keys
-- on: NULL on a voided/uncollectible stripe_tax invoice that still carries a
-- tax_transaction_id means "reversal not yet confirmed" — the sweep re-drives
-- the reversal (idempotent at Stripe via the invoice-stable reference) and
-- stamps tax_reversed_at on success (or when there is nothing left to reverse),
-- which drops the row out of the scan. Mirrors how the commit reconciler keys
-- on tax_transaction_id being populated.
--
-- Nullable + no backfill: an invoice that was never voided/uncollectible, or
-- has no committed tax transaction, simply has none. Existing reversed invoices
-- read NULL but fall out of the sweep's 24h freshness window, so they are not
-- re-reversed (and a re-reversal would be a Stripe-deduped no-op regardless).
ALTER TABLE invoices ADD COLUMN tax_reversed_at TIMESTAMPTZ;
