-- Denormalize the billing timezone onto each invoice — the peer of the
-- subscription's billing_timezone snapshot (ADR-074, migration 0133). The
-- invoice's billing_period_start/end are civil-midnight boundaries in the
-- owning subscription's billing TZ; billing_period_display (the inclusive
-- "Jun 1 – Jun 30" string, computed on read) must be rendered in THAT zone,
-- not the live tenant TZ, or the inclusive last-day step lands a day off once
-- a tenant changes its timezone. Copied from the subscription at invoice
-- creation and immutable thereafter (an invoice is a historical document).
--
-- Deliberately NO backfill. An existing invoice's period was computed under
-- whatever timezone was live when it was generated — which is NOT recoverable
-- from stored data (the subscription's snapshot was itself backfilled to the
-- tenant's CURRENT tz in 0133, which may differ from the tz the invoice's
-- period used). Leaving the column NULL makes the read path fall back to the
-- live tenant TZ — exactly what these invoices already display today, so there
-- is zero change for existing rows. Only invoices created after this migration
-- (from subscriptions carrying a proper snapshot) render in the anchor zone.
ALTER TABLE invoices ADD COLUMN billing_timezone TEXT;
