-- Drop the per-subscription billing_timezone snapshot (ADR-077 supersedes
-- ADR-074). No peer billing platform anchors each subscription in its own
-- frozen timezone; the billing anchor is a UTC instant everywhere, and the
-- one timezone a tenant bills in is an ORG-level setting (default UTC),
-- resolved live at compute time. The per-sub snapshot bought nothing the
-- org timezone doesn't, and its display divergence (a running sub rendering
-- in a zone different from the live org setting) was the sole source of a
-- ~8-bug render class. Billing math now anchors on the org timezone; the
-- resolved zone is denormalized onto the INVOICE at issue (0134) for
-- historical stability, which is where document-date stability actually
-- belongs.
--
-- Column 0133 added ~days ago on the same arc, pre-launch, zero customers —
-- no live subscription data depends on it.
ALTER TABLE subscriptions DROP COLUMN IF EXISTS billing_timezone;
