-- Additional billing-email recipients (ADR-082, design-cc-emails.md).
-- CC'd on billing documents and billing-state emails (invoice, receipt,
-- dunning warning/escalation, payment failed, credit note) — never on
-- credential-bearing emails (setup links, password reset, invites).
--
-- TEXT, not TEXT[]: the value is the SAME-ENCRYPTOR ciphertext of a
-- JSON string array, riding encryptCustomer/decryptCustomer exactly
-- like the sibling email column (plaintext JSON when no encryptor is
-- configured — self-host semantics unchanged). A plaintext array would
-- leak in a dump exactly the PII the primary email column protects.
-- Cap (10) and per-entry validation live in the customer service —
-- a DB CHECK cannot inspect ciphertext.
ALTER TABLE customers ADD COLUMN additional_emails TEXT NOT NULL DEFAULT '';
