-- Per-invoice auto-charge claim lease (HA-readiness hazard #1).
--
-- The auto-charge sweep was the one lock-gated money path with no row
-- claim: a Postgres-failover dual-leader window could double-charge one
-- invoice (leader A's UNKNOWN outcome bumps updated_at via
-- UpdatePayment; leader B's post-credit-apply refresh then mints a
-- DIFFERENT Stripe idempotency key). processAutoCharge now takes a
-- per-invoice CAS claim on this column before entering the charge leg —
-- dunning-shaped exactly-once, lease-backed so a crashed leader's claim
-- self-heals.
--
-- Deliberately NOT claim-in-list: the list methods are shared with
-- dunning enrollment (EnrollStalledForDunning), which a claiming list
-- would starve, and a batch-stamped lease cannot cover a serial
-- 50-invoice charge loop (adversarial review, 2026-07-06).
--
-- Never exposed: not in invCols, domain.Invoice, or the API. Claim and
-- release deliberately do not touch updated_at — the Stripe idempotency
-- key derives from it, and key stability across claim windows is what
-- makes a re-claimed retry converge on the SAME PaymentIntent.
ALTER TABLE invoices ADD COLUMN auto_charge_claimed_until TIMESTAMPTZ;
