-- Persist the actually-billed NOMINAL per-unit rate on flat-mode usage lines,
-- so the invoice unit-price column shows the clean configured rate (e.g.
-- 0.0003 decimal-cents = $0.000003/token = $3.00/1M) instead of the EFFECTIVE
-- amount÷quantity rate, which is a repeating decimal inflated by the
-- cent-rounding of the line total (ADR-054 re-examination, 2026-07-07).
--
-- STAMPED at build time, NOT derivable on read: a CustomerPriceOverride
-- (domain.CustomerPriceOverride.ApplyTo) swaps the price while PRESERVING the
-- rating_rule_versions row id the line stores, so reading that row back yields
-- LIST price, not the negotiated price actually billed. The engine stamps the
-- override-applied rule.FlatAmountCents, so this column holds the real billed
-- rate on negotiated lines.
--
-- NULL for every line without a single configured rate — base_fee/proration
-- (the effective per-seat amount is the honest figure; the full plan price
-- would misrepresent a prorated line), graduated/package usage (blended rate,
-- no single nominal), add_on/discount/tax (whole-cent unit already equals the
-- nominal). Those fall back to EffectiveUnitAmountDecimal, i.e. today's
-- behavior. Decimal cents, same units as unit_amount_decimal (ADR-045/054).
ALTER TABLE invoice_line_items ADD COLUMN nominal_unit_amount_decimal NUMERIC;
