-- audit_log: take the UPDATE/DELETE/TRUNCATE grants away from the runtime role.
--
-- The append-only guarantee has been enforced by triggers alone since 0011
-- (BEFORE UPDATE OR DELETE, row-level) and 0115 (BEFORE TRUNCATE, statement-
-- level). Both hold even for a role that bypasses RLS -- but they were the ONLY
-- barrier: 0001's grant loop ran `GRANT ALL ON TABLE <every table> TO velox_app`,
-- and 0115's own header admits the TRUNCATE privilege came "from the original
-- GRANT ALL, never revoked". A single dropped or disabled trigger (a bad
-- migration, an `ALTER TABLE ... DISABLE TRIGGER`, a restore that omits them)
-- would leave the tamper-evidence log writable by the very role that serves
-- customer traffic.
--
-- The privilege system and the triggers are INDEPENDENT enforcement mechanisms
-- with independent failure modes, so this is not belt-and-suspenders -- it is the
-- difference between one barrier and two. After this migration:
--
--   * velox_app (runtime)     -> blocked at the PERMISSION check (SQLSTATE 42501,
--                               "permission denied for table audit_log"), before
--                               any trigger runs. Layer 1.
--   * table owner / superuser -> still blocked by the triggers (SQLSTATE P0001,
--                               "audit_log is append-only"). Layer 2.
--
-- Nothing in the application updates, deletes or truncates audit_log -- the
-- append-only writer only ever INSERTs, so SELECT and INSERT are deliberately
-- kept. Legitimate retention purges remain a DB-admin operation performed as the
-- table owner (drop the triggers, delete, recreate), exactly as documented in
-- 0011; the owner's privileges are untouched by this REVOKE.
--
-- velox_app is a hard requirement of 0001 (its grant loop fails without the
-- role), so no role-exists guard is needed here.
REVOKE UPDATE, DELETE, TRUNCATE ON audit_log FROM velox_app;
